window.MAXIMUM_PRODUCTS = [
  {
    "id": 1,
    "numero": 1,
    "nombreOriginal": "Motor Cool 60%",
    "nombre": "Refrigerante Motor Cool 60% para GNV/GLP",
    "descripcion": "",
    "image": "imgproductos/creativo_1.jpeg",
    "alt": "Refrigerante Motor Cool 60% para GNV/GLP",
    "status": "hidden",
    "slug": "refrigerante-motor-cool-60-para-gnvglp",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE 60_ MAXIMUM (4).pdf"
  },
  {
    "id": 2,
    "numero": 2,
    "nombreOriginal": "Motor Cool HD Heavy Duty Vehículos Europeos",
    "nombre": "Refrigerante Motor Cool HD 55% para Vehículos Europeos",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_2.jpg",
    "alt": "Refrigerante Motor Cool HD 55% para Vehículos Europeos",
    "status": "valid",
    "slug": "refrigerante-motor-cool-hd-55-para-vehculos-europeos",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 1,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA COMPLETA DE 55_ NOAT - NITRITO MAXIMUM 3.pdf"
  },
  {
    "id": 3,
    "numero": 3,
    "nombreOriginal": "Antifreeze & Coolant 50%",
    "nombre": "Refrigerante Antifreeze & Coolant 50% para Vehículos Asiáticos",
    "descripcion": "",
    "image": "imgproductos/creativo_3.png",
    "alt": "Refrigerante Antifreeze & Coolant 50% para Vehículos Asiáticos",
    "status": "hidden",
    "slug": "refrigerante-antifreeze-coolant-50-para-vehculos-asiticos",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA COMPLETA DE 50_  11.pdf"
  },
  {
    "id": 4,
    "numero": 4,
    "nombreOriginal": "Trion",
    "nombre": "Silicona Premium Trion 343°C",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_4.png",
    "alt": "Silicona Premium Trion 343°C",
    "status": "valid",
    "slug": "silicona-premium-trion-343c",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 1,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA Tecnica SILICONA PARA EMPAQUETADURA TRION MAXIMUM_17.pdf"
  },
  {
    "id": 5,
    "numero": 5,
    "nombreOriginal": "Agua Químicamente Pura",
    "nombre": "Agua Químicamente Pura Desionizada",
    "descripcion": "",
    "image": "imgproductos/creativo_5.jpg",
    "alt": "Agua Químicamente Pura Desionizada",
    "status": "hidden",
    "slug": "agua-qumicamente-pura-desionizada",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 1,
    "pdf": null
  },
  {
    "id": 6,
    "numero": 6,
    "nombreOriginal": "Grasa de Cadena Multipropósito",
    "nombre": "Grasa de Cadena Multipropósito con Lithium Grease",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_6.jpg",
    "alt": "Grasa de Cadena Multipropósito con Lithium Grease",
    "status": "valid",
    "slug": "grasa-de-cadena-multipropsito-con-lithium-grease",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA MULTIPROPOSITO (5).pdf"
  },
  {
    "id": 7,
    "numero": 7,
    "nombreOriginal": "Gralimax Complejo de Litio",
    "nombre": "Grasa Gralimax Complejo de Litio NLGI 3 EP3 Grasa Azul",
    "descripcion": "",
    "image": "imgproductos/nuevos/grasa_hp3_azul_mockup.png",
    "alt": "Grasa Gralimax Complejo de Litio NLGI 3 EP3 Grasa Azul",
    "status": "valid",
    "slug": "grasa-gralimax-complejo-de-litio-nlgi-3-ep3",
    "category": "Grasas",
    "featured": true,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 8,
    "numero": 8,
    "nombreOriginal": "Xtrem 5.0",
    "nombre": "Refrigerante Xtrem 5.0 para Motos",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_8.jpg",
    "alt": "Refrigerante Xtrem 5.0 para Motos",
    "status": "valid",
    "slug": "refrigerante-xtrem-50-para-motos",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 9,
    "numero": 9,
    "nombreOriginal": "Stop Frenomax DOT4",
    "nombre": "Líquido para Frenos Frenomax DOT 4",
    "descripcion": "",
    "image": "imgproductos/creativo_9.png",
    "alt": "Líquido para Frenos Frenomax DOT 4",
    "status": "hidden",
    "slug": "lquido-para-frenos-frenomax-dot-4",
    "category": "Frenos",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 10,
    "numero": 10,
    "nombreOriginal": "Ultra Black / Grey Force",
    "nombre": "Silicona para Empaquetadura Ultra Black / Grey Force",
    "descripcion": "",
    "image": "imgproductos/creativo_10.jpeg",
    "alt": "Silicona para Empaquetadura Ultra Black / Grey Force",
    "status": "hidden",
    "slug": "silicona-para-empaquetadura-ultra-black-grey-force",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 1,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA SILICONA PARA EMPAQUETADURA, GREY FORCE - ULTRA BLACK. (6)"
  },
  {
    "id": 11,
    "numero": 11,
    "nombreOriginal": "Antifreeze & Coolant 33%",
    "nombre": "Refrigerante Antifreeze & Coolant 33% Verde",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_11.jpg",
    "alt": "Refrigerante Antifreeze & Coolant 33% Verde",
    "status": "valid",
    "slug": "refrigerante-antifreeze-coolant-33-verde",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE 33_ MAXIMUM_1.pdf"
  },
  {
    "id": 12,
    "numero": 12,
    "nombreOriginal": "Gralimax Grasa de Lithium EP2",
    "nombre": "Grasa Gralimax de Litio Multipropósito 200°C",
    "descripcion": "",
    "image": "imgproductos/creativo_12.png",
    "alt": "Grasa Gralimax de Litio Multipropósito 200°C",
    "status": "hidden",
    "slug": "grasa-gralimax-de-litio-multipropsito-200c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA MULTIPROPOSITO (5).pdf"
  },
  {
    "id": 13,
    "numero": 13,
    "nombreOriginal": "Estado Zero",
    "nombre": "Limpia Contactos Electrónicos Estado Zero",
    "descripcion": "",
    "image": "imgproductos/creativo_13.jpeg",
    "alt": "Limpia Contactos Electrónicos Estado Zero",
    "status": "hidden",
    "slug": "limpia-contactos-electrnicos-estado-zero",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE LIMPIACONTACTOS ESTADO ZERO(8).pdf"
  },
  {
    "id": 14,
    "numero": 14,
    "nombreOriginal": "Antifreeze & Coolant 33%",
    "nombre": "Refrigerante Antifreeze & Coolant 33% Rojo",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_14.jpg",
    "alt": "Refrigerante Antifreeze & Coolant 33% Rojo",
    "status": "valid",
    "slug": "refrigerante-antifreeze-coolant-33-rojo",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE 33_ MAXIMUM_1.pdf"
  },
  {
    "id": 15,
    "numero": 15,
    "nombreOriginal": "Gralimax Grasa de Lithium Multipropósito",
    "nombre": "Grasa Gralimax de Litio Multipropósito 200°C",
    "descripcion": "",
    "image": "imgproductos/creativo_15.png",
    "alt": "Grasa Gralimax de Litio Multipropósito 200°C",
    "status": "hidden",
    "slug": "grasa-gralimax-de-litio-multipropsito-200c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA MULTIPROPOSITO (5).pdf"
  },
  {
    "id": 16,
    "numero": 16,
    "nombreOriginal": "Carbuchock Cleaner",
    "nombre": "Limpiador de Carburador Carbuchock Cleaner",
    "descripcion": "",
    "image": "imgproductos/creativo_16.jpeg",
    "alt": "Limpiador de Carburador Carbuchock Cleaner",
    "status": "hidden",
    "slug": "limpiador-de-carburador-carbuchock-cleaner",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA LIMPIADOR DE CARBURADOR (12).pdf"
  },
  {
    "id": 17,
    "numero": 17,
    "nombreOriginal": "Refrigerante para Radiador Ice Blue",
    "nombre": "Refrigerante para Radiador Ice Blue para Motos",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_17.jpg",
    "alt": "Refrigerante para Radiador Ice Blue para Motos",
    "status": "valid",
    "slug": "refrigerante-para-radiador-ice-blue-para-motos",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 1,
    "pdf": "FICHAS TECNICAS MAXIMUM/ice blue ficha completa.pdf"
  },
  {
    "id": 18,
    "numero": 18,
    "nombreOriginal": "Nano Coating",
    "nombre": "Nano Coating Protección Total",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_18.png",
    "alt": "Nano Coating Protección Total",
    "status": "valid",
    "slug": "nano-coating-proteccin-total",
    "category": "Otros",
    "featured": false,
    "orderPriority": 1,
    "pdf": null
  },
  {
    "id": 19,
    "numero": 19,
    "nombreOriginal": "Stop DOT4 Ultra",
    "nombre": "Líquido de Frenos Stop DOT 4 Ultra",
    "descripcion": "",
    "image": "imgproductos/creativo_19.jpeg",
    "alt": "Líquido de Frenos Stop DOT 4 Ultra",
    "status": "hidden",
    "slug": "lquido-de-frenos-stop-dot-4-ultra",
    "category": "Frenos",
    "featured": false,
    "orderPriority": 1,
    "pdf": null
  },
  {
    "id": 20,
    "numero": 20,
    "nombreOriginal": "Motor HD Cool Heavy Duty Diésel",
    "nombre": "Refrigerante Motor Cool HD Diésel 55%",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_20.jpg",
    "alt": "Refrigerante Motor Cool HD Diésel 55%",
    "status": "valid",
    "slug": "refrigerante-motor-cool-hd-disel-55",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA COMPLETA DE 55_ NOAT - NITRITO MAXIMUM 3.pdf"
  },
  {
    "id": 21,
    "numero": 21,
    "nombreOriginal": "Shampoo High Eficiency",
    "nombre": "Shampoo para Auto High Eficiency 1 Lt",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_21.png",
    "alt": "Shampoo para Auto High Eficiency 1 Lt",
    "status": "valid",
    "slug": "shampoo-para-auto-high-eficiency-1-lt",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 1,
    "pdf": null
  },
  {
    "id": 22,
    "numero": 22,
    "nombreOriginal": "Motor Cool GNV/GLP",
    "nombre": "Refrigerante Motor Cool para GNV/GLP 60%",
    "descripcion": "",
    "image": "imgproductos/creativo_22.jpeg",
    "alt": "Refrigerante Motor Cool para GNV/GLP 60%",
    "status": "hidden",
    "slug": "refrigerante-motor-cool-para-gnvglp-60",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 23,
    "numero": 23,
    "nombreOriginal": "Refrigerante para Radiador Ice Blue",
    "nombre": "Refrigerante para Radiador Ice Blue 1 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_23.jpg",
    "alt": "Refrigerante para Radiador Ice Blue 1 Galón",
    "status": "valid",
    "slug": "refrigerante-para-radiador-ice-blue-1-galn",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/ice blue ficha completa.pdf"
  },
  {
    "id": 24,
    "numero": 24,
    "nombreOriginal": "Car Wax Scratch Out",
    "nombre": "Removedor de Rayones Car Wax Scratch Out",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_24.png",
    "alt": "Removedor de Rayones Car Wax Scratch Out",
    "status": "valid",
    "slug": "removedor-de-rayones-car-wax-scratch-out",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 25,
    "numero": 25,
    "nombreOriginal": "Agua Químicamente Pura",
    "nombre": "Agua Químicamente Pura Desionizada y Desmineralizada",
    "descripcion": "",
    "image": "imgproductos/creativo_25.jpg",
    "alt": "Agua Químicamente Pura Desionizada y Desmineralizada",
    "status": "hidden",
    "slug": "agua-qumicamente-pura-desionizada-y-desmineralizada",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 26,
    "numero": 26,
    "nombreOriginal": "Limpia Parabrisas",
    "nombre": "Limpia Parabrisas Concentrado 1:100",
    "descripcion": "",
    "image": "imgproductos/creativo_26.png",
    "alt": "Limpia Parabrisas Concentrado 1:100",
    "status": "hidden",
    "slug": "limpia-parabrisas-concentrado-1100",
    "category": "Otros",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 27,
    "numero": 27,
    "nombreOriginal": "Antifreeze & Coolant 50%",
    "nombre": "Refrigerante Antifreeze & Coolant 50% Rojo",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_27.jpg",
    "alt": "Refrigerante Antifreeze & Coolant 50% Rojo",
    "status": "valid",
    "slug": "refrigerante-antifreeze-coolant-50-rojo",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA COMPLETA DE 50_  11.pdf"
  },
  {
    "id": 28,
    "numero": 28,
    "nombreOriginal": "Gralimax Grasa de Lithium EP2",
    "nombre": "Grasa Gralimax de Litio EP2 con Molibdeno y Grafito 200°C",
    "descripcion": "",
    "image": "imgproductos/nuevos/grasa_ep2_molibdeno.png",
    "alt": "Grasa Gralimax de Litio EP2 con Molibdeno y Grafito 200°C",
    "status": "valid",
    "slug": "grasa-gralimax-de-litio-ep2-con-molibdeno-y-grafito-200c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 1,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA GRAFITO (6).pdf"
  },
  {
    "id": 29,
    "numero": 29,
    "nombreOriginal": "Motor HD Cool Heavy Duty Vehículos Europeos Violet",
    "nombre": "Refrigerante Motor Cool HD Vehículos Europeos Violet 55%",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_29.jpg",
    "alt": "Refrigerante Motor Cool HD Vehículos Europeos Violet 55%",
    "status": "valid",
    "slug": "refrigerante-motor-cool-hd-vehculos-europeos-violet-55",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA COMPLETA DE 55_ NOAT - NITRITO MAXIMUM 3.pdf"
  },
  {
    "id": 30,
    "numero": 30,
    "nombreOriginal": "Gralimax Grasa de Lithium H3",
    "nombre": "Grasa Gralimax de Litio H3 200°C",
    "descripcion": "",
    "image": "imgproductos/nuevos/grasa_h3_amarilla.png",
    "alt": "Grasa Gralimax de Litio H3 200°C",
    "status": "valid",
    "slug": "grasa-gralimax-de-litio-h3-200c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA H3(7).pdf"
  },
  {
    "id": 31,
    "numero": 31,
    "nombreOriginal": "Potencia Estable",
    "nombre": "Creativo Potencia Estable Antifreeze & Coolant 50%",
    "descripcion": "",
    "image": "imgproductos/creativo_31.jpeg",
    "alt": "Creativo Potencia Estable Antifreeze & Coolant 50%",
    "status": "hidden",
    "slug": "creativo-potencia-estable-antifreeze-coolant-50",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 32,
    "numero": 32,
    "nombreOriginal": "Ice Green Taxi Fresh",
    "nombre": "Refrigerante para Radiador Ice Green Taxi Fresh 1 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_32.jpg",
    "alt": "Refrigerante para Radiador Ice Green Taxi Fresh 1 Galón",
    "status": "valid",
    "slug": "refrigerante-para-radiador-ice-green-taxi-fresh-1-galn",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/ice blue ficha completa.pdf"
  },
  {
    "id": 33,
    "numero": 33,
    "nombreOriginal": "Motor Cool 60%",
    "nombre": "Refrigerante Motor Cool 60% para GNV/GLP 1 QT",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_33.png",
    "alt": "Refrigerante Motor Cool 60% para GNV/GLP 1 QT",
    "status": "valid",
    "slug": "refrigerante-motor-cool-60-para-gnvglp-1-qt",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE 60_ MAXIMUM (4).pdf"
  },
  {
    "id": 34,
    "numero": 34,
    "nombreOriginal": "Motor HD Cool Heavy Duty Vehículos Multimarca Amarillo",
    "nombre": "Refrigerante Motor HD Cool Heavy Duty Vehículos Multimarca Amarillo 55%",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_34.jpg",
    "alt": "Refrigerante Motor HD Cool Heavy Duty Vehículos Multimarca Amarillo 55%",
    "status": "valid",
    "slug": "refrigerante-motor-hd-cool-heavy-duty-vehculos-multimarca-amarillo-55",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA COMPLETA DE 55_ OEM , 2026.pdf"
  },
  {
    "id": 35,
    "numero": 35,
    "nombreOriginal": "Gralimax Grasa de Lithium EP2",
    "nombre": "Grasa Gralimax de Litio EP2 NLGI 2 Multipropósito 200°C",
    "descripcion": "",
    "image": "imgproductos/nuevos/grasa_ep2_amarilla_mockup.png",
    "alt": "Grasa Gralimax de Litio EP2 NLGI 2 Multipropósito 200°C",
    "status": "valid",
    "slug": "grasa-gralimax-de-litio-ep2-nlgi-2-multipropsito-200c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA MULTIPROPOSITO (5).pdf"
  },
  {
    "id": 36,
    "numero": 36,
    "nombreOriginal": "Motor Cool 60%",
    "nombre": "Refrigerante Motor Cool 60% para GNV/GLP 1 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_36.png",
    "alt": "Refrigerante Motor Cool 60% para GNV/GLP 1 Galón",
    "status": "valid",
    "slug": "refrigerante-motor-cool-60-para-gnvglp-1-galn",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE 60_ MAXIMUM (4).pdf"
  },
  {
    "id": 37,
    "numero": 37,
    "nombreOriginal": "Gralimax Grasa de Lithium H3",
    "nombre": "Grasa Gralimax de Litio H3 260°C",
    "descripcion": "",
    "image": "imgproductos/creativo_37.png",
    "alt": "Grasa Gralimax de Litio H3 260°C",
    "status": "hidden",
    "slug": "grasa-gralimax-de-litio-h3-260c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA H3(7).pdf"
  },
  {
    "id": 38,
    "numero": 38,
    "nombreOriginal": "Shampoo Super Concentrado Brillo Cerámico",
    "nombre": "Shampoo Super Concentrado Brillo Cerámico 5 Galones",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_38.jpg",
    "alt": "Shampoo Super Concentrado Brillo Cerámico 5 Galones",
    "status": "valid",
    "slug": "shampoo-super-concentrado-brillo-cermico-5-galones",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 39,
    "numero": 39,
    "nombreOriginal": "Antifreeze & Coolant 33%",
    "nombre": "Refrigerante Antifreeze & Coolant 33% Rojo 1 Galón",
    "descripcion": "",
    "image": "imgproductos/creativo_39.png",
    "alt": "Refrigerante Antifreeze & Coolant 33% Rojo 1 Galón",
    "status": "hidden",
    "slug": "refrigerante-antifreeze-coolant-33-rojo-1-galn",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE 33_ MAXIMUM_1.pdf"
  },
  {
    "id": 40,
    "numero": 40,
    "nombreOriginal": "Ice Orange",
    "nombre": "Refrigerante para Radiador Ice Orange 1 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_40.jpg",
    "alt": "Refrigerante para Radiador Ice Orange 1 Galón",
    "status": "valid",
    "slug": "refrigerante-para-radiador-ice-orange-1-galn",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/ice blue ficha completa.pdf"
  },
  {
    "id": 41,
    "numero": 41,
    "nombreOriginal": "Speedy Klean Limpiador Magnético de Ventana",
    "nombre": "Limpiador Magnético de Ventana Speedy Klean",
    "descripcion": "",
    "image": "imgproductos/creativo_41.png",
    "alt": "Limpiador Magnético de Ventana Speedy Klean",
    "status": "hidden",
    "slug": "limpiador-magntico-de-ventana-speedy-klean",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 42,
    "numero": 42,
    "nombreOriginal": "Motor HD Cool Heavy Duty Vehículos Europeos Pink",
    "nombre": "Refrigerante Motor HD Cool Heavy Duty Vehículos Europeos Pink 55%",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_42.jpg",
    "alt": "Refrigerante Motor HD Cool Heavy Duty Vehículos Europeos Pink 55%",
    "status": "valid",
    "slug": "refrigerante-motor-hd-cool-heavy-duty-vehculos-europeos-pink-55",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA COMPLETA DE 55_ NOAT - NITRITO MAXIMUM 3.pdf"
  },
  {
    "id": 43,
    "numero": 43,
    "nombreOriginal": "Gralimax Grasa de Lithium H3",
    "nombre": "Grasa Gralimax de Litio H3 260°C",
    "descripcion": "",
    "image": "imgproductos/nuevos/grasa_h3_azul.png",
    "alt": "Grasa Gralimax de Litio H3 260°C",
    "status": "valid",
    "slug": "grasa-gralimax-de-litio-h3-260c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA H3(7).pdf"
  },
  {
    "id": 44,
    "numero": 44,
    "nombreOriginal": "Antifreeze & Coolant 50%",
    "nombre": "Refrigerante Antifreeze & Coolant 50% Verde 1 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_44.jpg",
    "alt": "Refrigerante Antifreeze & Coolant 50% Verde 1 Galón",
    "status": "valid",
    "slug": "refrigerante-antifreeze-coolant-50-verde-1-galn",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA COMPLETA DE 50_  11.pdf"
  },
  {
    "id": 45,
    "numero": 45,
    "nombreOriginal": "Speedy Klean Mopa Centrífuga 360",
    "nombre": "Mopa Centrífuga 360 Speedy Klean",
    "descripcion": "",
    "image": "imgproductos/creativo_45.png",
    "alt": "Mopa Centrífuga 360 Speedy Klean",
    "status": "hidden",
    "slug": "mopa-centrfuga-360-speedy-klean",
    "category": "Accesorios",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 46,
    "numero": 46,
    "nombreOriginal": "Ice Dark",
    "nombre": "Refrigerante para Radiador Ice Dark 1 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_46.jpg",
    "alt": "Refrigerante para Radiador Ice Dark 1 Galón",
    "status": "valid",
    "slug": "refrigerante-para-radiador-ice-dark-1-galn",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/ice blue ficha completa.pdf"
  },
  {
    "id": 47,
    "numero": 47,
    "nombreOriginal": "Gralimax Grasa de Lithium EP2 Molibdeno Grafito",
    "nombre": "Grasa Gralimax de Litio EP2 con Molibdeno y Grafito 200°C",
    "descripcion": "",
    "image": "imgproductos/nuevos/grasa_ep2_molibdeno.png",
    "alt": "Grasa Gralimax de Litio EP2 con Molibdeno y Grafito 200°C",
    "status": "valid",
    "slug": "grasa-gralimax-de-litio-ep2-con-molibdeno-y-grafito-200c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA GRAFITO (6).pdf"
  },
  {
    "id": 48,
    "numero": 48,
    "nombreOriginal": "Ice Violet",
    "nombre": "Refrigerante para Radiador Ice Violet 1 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_48.jpg",
    "alt": "Refrigerante para Radiador Ice Violet 1 Galón",
    "status": "valid",
    "slug": "refrigerante-para-radiador-ice-violet-1-galn",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/ice blue ficha completa.pdf"
  },
  {
    "id": 49,
    "numero": 49,
    "nombreOriginal": "Antifreeze & Coolant 50% Balde",
    "nombre": "Refrigerante Antifreeze & Coolant 50% Balde 5 Galones",
    "descripcion": "",
    "image": "imgproductos/nuevos/balde_ac50_rojo.png",
    "alt": "Refrigerante Antifreeze & Coolant 50% Balde 5 Galones",
    "status": "valid",
    "slug": "refrigerante-antifreeze-coolant-50-verde-balde-5-galones",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA COMPLETA DE 50_  11.pdf"
  },
  {
    "id": 50,
    "numero": 50,
    "nombreOriginal": "Motor HD Cool Heavy Duty Vehículos Americanos Orange",
    "nombre": "Refrigerante Motor HD Cool Heavy Duty Vehículos Americanos Orange 55%",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_50.jpg",
    "alt": "Refrigerante Motor HD Cool Heavy Duty Vehículos Americanos Orange 55%",
    "status": "valid",
    "slug": "refrigerante-motor-hd-cool-heavy-duty-vehculos-americanos-orange-55",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA COMPLETA DE 55_ OEM , 2026.pdf"
  },
  {
    "id": 51,
    "numero": 51,
    "nombreOriginal": "Carbu Chock Cleaner Limpiador de Carburador",
    "nombre": "Limpiador de Carburador Carbu Chock Cleaner aroma a limón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_51.png",
    "alt": "Limpiador de Carburador Carbu Chock Cleaner aroma a limón",
    "status": "valid",
    "slug": "limpiador-de-carburador-carbu-chock-cleaner-aroma-a-limn",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA LIMPIADOR DE CARBURADOR (12).pdf"
  },
  {
    "id": 52,
    "numero": 52,
    "nombreOriginal": "Antifreeze & Coolant 17%",
    "nombre": "Refrigerante Antifreeze & Coolant 17% Verde 1 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_52.jpg",
    "alt": "Refrigerante Antifreeze & Coolant 17% Verde 1 Galón",
    "status": "valid",
    "slug": "refrigerante-antifreeze-coolant-17-verde-1-galn",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE 17_ MAXIMUM_1.pdf"
  },
  {
    "id": 53,
    "numero": 53,
    "nombreOriginal": "Plastic & Leather Renewer",
    "nombre": "Renovador de Plástico y Cuero Plastic & Leather Renewer",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_53.png",
    "alt": "Renovador de Plástico y Cuero Plastic & Leather Renewer",
    "status": "valid",
    "slug": "renovador-de-plstico-y-cuero-plastic-leather-renewer",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 54,
    "numero": 54,
    "nombreOriginal": "Máxima Protección",
    "nombre": "Creativo Máxima Protección Antifreeze & Coolant 33%",
    "descripcion": "",
    "image": "imgproductos/creativo_54.jpeg",
    "alt": "Creativo Máxima Protección Antifreeze & Coolant 33%",
    "status": "hidden",
    "slug": "creativo-mxima-proteccin-antifreeze-coolant-33",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 55,
    "numero": 55,
    "nombreOriginal": "EGA964 Etilenglicol Aditivado",
    "nombre": "Refrigerante Concentrado EGA964 Etilenglicol Aditivado Rojo Reflex",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_55.jpg",
    "alt": "Refrigerante Concentrado EGA964 Etilenglicol Aditivado Rojo Reflex",
    "status": "valid",
    "slug": "refrigerante-concentrado-ega964-etilenglicol-aditivado-rojo-reflex",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 56,
    "numero": 56,
    "nombreOriginal": "Trion Premium",
    "nombre": "Silicona Premium Trion 343°C",
    "descripcion": "",
    "image": "imgproductos/creativo_56.png",
    "alt": "Silicona Premium Trion 343°C",
    "status": "hidden",
    "slug": "silicona-premium-trion-343c",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA Tecnica SILICONA PARA EMPAQUETADURA TRION MAXIMUM_17.pdf"
  },
  {
    "id": 57,
    "numero": 57,
    "nombreOriginal": "Motor HD Cool Heavy Duty Vehículos Asiáticos Green",
    "nombre": "Refrigerante Motor HD Cool Heavy Duty Vehículos Asiáticos Green 55%",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_57.jpg",
    "alt": "Refrigerante Motor HD Cool Heavy Duty Vehículos Asiáticos Green 55%",
    "status": "valid",
    "slug": "refrigerante-motor-hd-cool-heavy-duty-vehculos-asiticos-green-55",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA COMPLETA DE 55_ OEM , 2026.pdf"
  },
  {
    "id": 58,
    "numero": 58,
    "nombreOriginal": "Protector Total Mate",
    "nombre": "Protector Total Mate para interior y exterior",
    "descripcion": "",
    "image": "imgproductos/creativo_58.png",
    "alt": "Protector Total Mate para interior y exterior",
    "status": "hidden",
    "slug": "protector-total-mate-para-interior-y-exterior",
    "category": "Otros",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 59,
    "numero": 59,
    "nombreOriginal": "Ice Pink",
    "nombre": "Refrigerante para Radiador Ice Pink 1 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_59.jpg",
    "alt": "Refrigerante para Radiador Ice Pink 1 Galón",
    "status": "valid",
    "slug": "refrigerante-para-radiador-ice-pink-1-galn",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/ice blue ficha completa.pdf"
  },
  {
    "id": 60,
    "numero": 60,
    "nombreOriginal": "Gralimax Grasa de Lithium EP2 NLGI2 200°C",
    "nombre": "Grasa Gralimax de Litio EP2 NLGI2 200°C",
    "descripcion": "",
    "image": "imgproductos/nuevos/grasa_ep2_amarilla2.png",
    "alt": "Grasa Gralimax de Litio EP2 NLGI2 200°C",
    "status": "valid",
    "slug": "grasa-gralimax-de-litio-ep2-nlgi2-200c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA MULTIPROPOSITO (5).pdf"
  },
  {
    "id": 61,
    "numero": 61,
    "nombreOriginal": "Motor HD Cool Heavy Duty Vehículos Asiáticos Blue",
    "nombre": "Refrigerante Motor HD Cool Heavy Duty Vehículos Asiáticos Blue 55%",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_61.jpg",
    "alt": "Refrigerante Motor HD Cool Heavy Duty Vehículos Asiáticos Blue 55%",
    "status": "valid",
    "slug": "refrigerante-motor-hd-cool-heavy-duty-vehculos-asiticos-blue-55",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA COMPLETA DE 55_ OEM , 2026.pdf"
  },
  {
    "id": 62,
    "numero": 62,
    "nombreOriginal": "Agua Químicamente Pura",
    "nombre": "Agua Químicamente Pura desionizada y desmineralizada 1 Galón / 5 Litros",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_62.jpg",
    "alt": "Agua Químicamente Pura desionizada y desmineralizada 1 Galón / 5 Litros",
    "status": "valid",
    "slug": "agua-qumicamente-pura-desionizada-y-desmineralizada-1-galn-5-litros",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 63,
    "numero": 63,
    "nombreOriginal": "Ice Blue 5 Galones",
    "nombre": "Refrigerante para Radiador Ice Blue 5 Galones",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_63.jpg",
    "alt": "Refrigerante para Radiador Ice Blue 5 Galones",
    "status": "valid",
    "slug": "refrigerante-para-radiador-ice-blue-5-galones",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/ice blue ficha completa.pdf"
  },
  {
    "id": 64,
    "numero": 64,
    "nombreOriginal": "Agua Químicamente Pura AQP-1QG",
    "nombre": "Agua Químicamente Pura AQP-1QG 1 Cuarto de Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_64.jpg",
    "alt": "Agua Químicamente Pura AQP-1QG 1 Cuarto de Galón",
    "status": "valid",
    "slug": "agua-qumicamente-pura-aqp-1qg-1-cuarto-de-galn",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 65,
    "numero": 65,
    "nombreOriginal": "Ice Yellow",
    "nombre": "Refrigerante para Radiador Ice Yellow 1 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_65.jpg",
    "alt": "Refrigerante para Radiador Ice Yellow 1 Galón",
    "status": "valid",
    "slug": "refrigerante-para-radiador-ice-yellow-1-galn",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/ice blue ficha completa.pdf"
  },
  {
    "id": 66,
    "numero": 66,
    "nombreOriginal": "Stop Líquido de Frenos DOT5.1",
    "nombre": "Líquido de Frenos Stop DOT5.1 Ultra 354 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_66.png",
    "alt": "Líquido de Frenos Stop DOT5.1 Ultra 354 ml",
    "status": "valid",
    "slug": "lquido-de-frenos-stop-dot51-ultra-354-ml",
    "category": "Frenos",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA LIQUIDO DE FRENOS (11).pdf"
  },
  {
    "id": 67,
    "numero": 67,
    "nombreOriginal": "Motor HD Cool Heavy Duty Vehículos Multimarca Rojo",
    "nombre": "Refrigerante Motor HD Cool Heavy Duty Vehículos Multimarca Rojo 55%",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_67.jpg",
    "alt": "Refrigerante Motor HD Cool Heavy Duty Vehículos Multimarca Rojo 55%",
    "status": "valid",
    "slug": "refrigerante-motor-hd-cool-heavy-duty-vehculos-multimarca-rojo-55",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA COMPLETA DE 55_ OEM , 2026.pdf"
  },
  {
    "id": 68,
    "numero": 68,
    "nombreOriginal": "Motor Cool 5 Galones GLP/GNV",
    "nombre": "Refrigerante Motor Cool GLP/GNV 60% 5 Galones",
    "descripcion": "",
    "image": "imgproductos/nuevos/balde_motorcool_glp.png",
    "alt": "Refrigerante Motor Cool GLP/GNV 60% 5 Galones",
    "status": "valid",
    "slug": "refrigerante-motor-cool-glpgnv-60-5-galones",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE 60_ MAXIMUM (4).pdf"
  },
  {
    "id": 69,
    "numero": 69,
    "nombreOriginal": "Injector Cleaner Gasolina",
    "nombre": "Limpiador de Inyectores Injector Cleaner Gasolina",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_69.png",
    "alt": "Limpiador de Inyectores Injector Cleaner Gasolina",
    "status": "valid",
    "slug": "limpiador-de-inyectores-injector-cleaner-gasolina",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 1,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA COMPLETA INYECTORES3.pdf"
  },
  {
    "id": 70,
    "numero": 70,
    "nombreOriginal": "Gralimax Grasa de Lithium EP2 NLGI2 200°C",
    "nombre": "Grasa Gralimax de Litio EP2 NLGI2 200°C",
    "descripcion": "",
    "image": "imgproductos/creativo_70.png",
    "alt": "Grasa Gralimax de Litio EP2 NLGI2 200°C",
    "status": "hidden",
    "slug": "grasa-gralimax-de-litio-ep2-nlgi2-200c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 71,
    "numero": 71,
    "nombreOriginal": "Gralimax Grasa de Lithium H3",
    "nombre": "Grasa Gralimax de Litio H3 260°C",
    "descripcion": "",
    "image": "imgproductos/nuevos/grasa_h3_amarilla.png",
    "alt": "Grasa Gralimax de Litio H3 260°C",
    "status": "valid",
    "slug": "grasa-gralimax-de-litio-h3-260c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA H3(7).pdf"
  },
  {
    "id": 72,
    "numero": 72,
    "nombreOriginal": "Gralimax Grasa de Lithium H3 Balde",
    "nombre": "Grasa Gralimax de Litio H3 NLGI2 260°C Balde",
    "descripcion": "",
    "image": "imgproductos/creativo_72.png",
    "alt": "Grasa Gralimax de Litio H3 NLGI2 260°C Balde",
    "status": "hidden",
    "slug": "grasa-gralimax-de-litio-h3-nlgi2-260c-balde",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA H3(7).pdf"
  },
  {
    "id": 73,
    "numero": 73,
    "nombreOriginal": "Creativo Ice Aditivados",
    "nombre": "Creativo Línea Ice Aditivados Ecológicos",
    "descripcion": "",
    "image": "imgproductos/creativo_73.jpeg",
    "alt": "Creativo Línea Ice Aditivados Ecológicos",
    "status": "hidden",
    "slug": "creativo-lnea-ice-aditivados-ecolgicos",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 74,
    "numero": 74,
    "nombreOriginal": "Ice Red",
    "nombre": "Refrigerante para Radiador Ice Red 1 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_74.jpg",
    "alt": "Refrigerante para Radiador Ice Red 1 Galón",
    "status": "valid",
    "slug": "refrigerante-para-radiador-ice-red-1-galn",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/ice blue ficha completa.pdf"
  },
  {
    "id": 75,
    "numero": 75,
    "nombreOriginal": "Gralimax Grasa de Lithium H3 Amarillo",
    "nombre": "Grasa Gralimax de Litio H3 260°C",
    "descripcion": "",
    "image": "imgproductos/nuevos/grasa_h3_roja.png",
    "alt": "Grasa Gralimax de Litio H3 260°C",
    "status": "valid",
    "slug": "grasa-gralimax-de-litio-h3-260c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA H3(7).pdf"
  },
  {
    "id": 76,
    "numero": 76,
    "nombreOriginal": "Gralimax Grasa de Lithium H3 Balde Azul",
    "nombre": "Grasa Gralimax de Litio H3 NLGI2 260°C Balde",
    "descripcion": "",
    "image": "imgproductos/creativo_76.png",
    "alt": "Grasa Gralimax de Litio H3 NLGI2 260°C Balde",
    "status": "hidden",
    "slug": "grasa-gralimax-de-litio-h3-nlgi2-260c-balde",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA H3(7).pdf"
  },
  {
    "id": 77,
    "numero": 77,
    "nombreOriginal": "Tambor Maximum",
    "nombre": "Tambor Maximum Tecnología Automotriz 200 Litros",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_77.png",
    "alt": "Tambor Maximum Tecnología Automotriz 200 Litros",
    "status": "valid",
    "slug": "tambor-maximum-tecnologa-automotriz",
    "category": "Presentaciones",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 78,
    "numero": 78,
    "nombreOriginal": "Motor HD Cool Heavy Duty Diesel 5 Galones",
    "nombre": "Refrigerante Motor HD Cool Heavy Duty Diesel 55% 5 Galones",
    "descripcion": "",
    "image": "imgproductos/nuevos/balde_hd_diesel.png",
    "alt": "Refrigerante Motor HD Cool Heavy Duty Diesel 55% 5 Galones",
    "status": "valid",
    "slug": "refrigerante-motor-hd-cool-heavy-duty-diesel-55-5-galones",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA COMPLETA DE 55_ NOAT - NITRITO MAXIMUM 3.pdf"
  },
  {
    "id": 79,
    "numero": 79,
    "nombreOriginal": "Gralimax Grasa de Lithium Multipropósito Amarillo",
    "nombre": "Grasa Gralimax de Litio Multipropósito 200°C",
    "descripcion": "",
    "image": "imgproductos/nuevos/grasa_ep2_amarilla_mockup.png",
    "alt": "Grasa Gralimax de Litio Multipropósito 200°C",
    "status": "valid",
    "slug": "grasa-gralimax-de-litio-multipropsito-200c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA MULTIPROPOSITO (5).pdf"
  },
  {
    "id": 80,
    "numero": 80,
    "nombreOriginal": "Gralimax Grasa de Lithium Multipropósito Amarillo",
    "nombre": "Grasa Gralimax de Litio Multipropósito 200°C",
    "descripcion": "",
    "image": "imgproductos/nuevos/grasa_ep2_roja_mockup.png",
    "alt": "Grasa Gralimax de Litio Multipropósito 200°C",
    "status": "valid",
    "slug": "grasa-gralimax-de-litio-multipropsito-200c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA MULTIPROPOSITO (5).pdf"
  },
  {
    "id": 81,
    "numero": 81,
    "nombreOriginal": "Gralimax Grasa de Lithium H3",
    "nombre": "Grasa Gralimax de Litio H3 260°C",
    "descripcion": "",
    "image": "imgproductos/nuevos/grasa_h3_roja.png",
    "alt": "Grasa Gralimax de Litio H3 260°C",
    "status": "valid",
    "slug": "grasa-gralimax-de-litio-h3-260c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA H3(7).pdf"
  },
  {
    "id": 82,
    "numero": 82,
    "nombreOriginal": "Gralimax Grasa de Lithium Multipropósito Roja",
    "nombre": "Grasa Gralimax de Litio Multipropósito 200°C",
    "descripcion": "",
    "image": "imgproductos/nuevos/grasa_ep2_azul.png",
    "alt": "Grasa Gralimax de Litio Multipropósito 200°C",
    "status": "valid",
    "slug": "grasa-gralimax-de-litio-multipropsito-200c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA MULTIPROPOSITO (5).pdf"
  },
  {
    "id": 83,
    "numero": 83,
    "nombreOriginal": "Gralimax Grasa de Lithium Multipropósito Balde Amarillo",
    "nombre": "Grasa Gralimax de Litio Multipropósito EP2 NLGI2 200°C Balde",
    "descripcion": "",
    "image": "imgproductos/creativo_83.png",
    "alt": "Grasa Gralimax de Litio Multipropósito EP2 NLGI2 200°C Balde",
    "status": "hidden",
    "slug": "grasa-gralimax-de-litio-multipropsito-ep2-nlgi2-200c-balde",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 84,
    "numero": 84,
    "nombreOriginal": "Gralimax Grasa de Lithium H3 Cartucho",
    "nombre": "Cartucho de Grasa Gralimax de Litio H3 260°C",
    "descripcion": "",
    "image": "imgproductos/creativo_84.png",
    "alt": "Cartucho de Grasa Gralimax de Litio H3 260°C",
    "status": "hidden",
    "slug": "cartucho-de-grasa-gralimax-de-litio-h3-260c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA H3(7).pdf"
  },
  {
    "id": 85,
    "numero": 85,
    "nombreOriginal": "Gralimax Grasa de Lithium Multipropósito Cartucho",
    "nombre": "Cartucho de Grasa Gralimax de Litio Multipropósito 200°C",
    "descripcion": "",
    "image": "imgproductos/creativo_85.png",
    "alt": "Cartucho de Grasa Gralimax de Litio Multipropósito 200°C",
    "status": "hidden",
    "slug": "cartucho-de-grasa-gralimax-de-litio-multipropsito-200c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA MULTIPROPOSITO (5).pdf"
  },
  {
    "id": 86,
    "numero": 86,
    "nombreOriginal": "Creativo Vehículos Asiáticos Verde OAT",
    "nombre": "Creativo Refrigerante Verde OAT para Vehículos Asiáticos",
    "descripcion": "",
    "image": "imgproductos/creativo_86.jpeg",
    "alt": "Creativo Refrigerante Verde OAT para Vehículos Asiáticos",
    "status": "hidden",
    "slug": "creativo-refrigerante-verde-oat-para-vehculos-asiticos",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 87,
    "numero": 87,
    "nombreOriginal": "Agua Químicamente Pura",
    "nombre": "Agua Químicamente Pura Maximum 5 Litros",
    "descripcion": "",
    "image": "imgproductos/creativo_87.jpg",
    "alt": "Agua Químicamente Pura Maximum 5 Litros",
    "status": "hidden",
    "slug": "agua-qumicamente-pura-maximum-5-litros",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 88,
    "numero": 88,
    "nombreOriginal": "Foam Cleaner Multipurpose",
    "nombre": "Espuma Limpiadora Multipropósito Foam Cleaner 600 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_88.png",
    "alt": "Espuma Limpiadora Multipropósito Foam Cleaner 600 ml",
    "status": "valid",
    "slug": "espuma-limpiadora-multipropsito-foam-cleaner-600-ml",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 89,
    "numero": 89,
    "nombreOriginal": "Grey Force",
    "nombre": "Silicona para Empaquetadura Grey Force 343°C 85 gr",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_89.png",
    "alt": "Silicona para Empaquetadura Grey Force 343°C 85 gr",
    "status": "valid",
    "slug": "silicona-para-empaquetadura-grey-force-343c-85-gr",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA SILICONA PARA EMPAQUETADURA, GREY FORCE - ULTRA BLACK. (6)"
  },
  {
    "id": 90,
    "numero": 90,
    "nombreOriginal": "Ultra Black",
    "nombre": "Silicona para Empaquetadura Ultra Black 343°C 85 gr",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_90.png",
    "alt": "Silicona para Empaquetadura Ultra Black 343°C 85 gr",
    "status": "valid",
    "slug": "silicona-para-empaquetadura-ultra-black-343c-85-gr",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA SILICONA PARA EMPAQUETADURA, GREY FORCE - ULTRA BLACK. (6)"
  },
  {
    "id": 91,
    "numero": 91,
    "nombreOriginal": "Stop DOT4 Ultra",
    "nombre": "Líquido de Frenos DOT4 Ultra 230°C 354 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_91.png",
    "alt": "Líquido de Frenos DOT4 Ultra 230°C 354 ml",
    "status": "valid",
    "slug": "lquido-de-frenos-dot4-ultra-230c-354-ml",
    "category": "Frenos",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA LIQUIDO DE FRENOS (11).pdf"
  },
  {
    "id": 92,
    "numero": 92,
    "nombreOriginal": "Estado Zero",
    "nombre": "Limpiacontactos Electrónicos Estado Zero Aroma Limón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_92.png",
    "alt": "Limpiacontactos Electrónicos Estado Zero Aroma Limón",
    "status": "valid",
    "slug": "limpiacontactos-electrnicos-estado-zero-aroma-limn",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE LIMPIACONTACTOS ESTADO ZERO(8).pdf"
  },
  {
    "id": 93,
    "numero": 93,
    "nombreOriginal": "Injector Cleaner Diesel Turbo Cargado",
    "nombre": "Limpiador de Inyectores Diesel Turbo Cargado 354 ml",
    "descripcion": "",
    "image": "imgproductos/creativo_93.png",
    "alt": "Limpiador de Inyectores Diesel Turbo Cargado 354 ml",
    "status": "hidden",
    "slug": "limpiador-de-inyectores-diesel-turbo-cargado-354-ml",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 94,
    "numero": 94,
    "nombreOriginal": "Kristal Clean",
    "nombre": "Limpia Parabrisas Kristal Clean 1 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_94.png",
    "alt": "Limpia Parabrisas Kristal Clean 1 Galón",
    "status": "valid",
    "slug": "limpia-parabrisas-kristal-clean-1-galn",
    "category": "Otros",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 95,
    "numero": 95,
    "nombreOriginal": "Kristal Clean foto real",
    "nombre": "Limpia Parabrisas Kristal Clean 1 Qt",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_95.png",
    "alt": "Limpia Parabrisas Kristal Clean 1 Qt",
    "status": "valid",
    "slug": "limpia-parabrisas-kristal-clean-1-qt",
    "category": "Otros",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 96,
    "numero": 96,
    "nombreOriginal": "Agua Químicamente Pura foto real",
    "nombre": "Agua Químicamente Pura Maximum 1 Qt",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_96.png",
    "alt": "Agua Químicamente Pura Maximum 1 Qt",
    "status": "valid",
    "slug": "agua-qumicamente-pura-maximum-1-qt",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 97,
    "numero": 97,
    "nombreOriginal": "Kristal Home",
    "nombre": "Limpiavidrios Kristal Home 650 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_97.png",
    "alt": "Limpiavidrios Kristal Home 650 ml",
    "status": "valid",
    "slug": "limpiavidrios-kristal-home-650-ml",
    "category": "Otros",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 98,
    "numero": 98,
    "nombreOriginal": "Shampoo Brillo Cerámico",
    "nombre": "Shampoo Súper Concentrado Brillo Cerámico 350 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_98.png",
    "alt": "Shampoo Súper Concentrado Brillo Cerámico 350 ml",
    "status": "valid",
    "slug": "shampoo-sper-concentrado-brillo-cermico-350-ml",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 99,
    "numero": 99,
    "nombreOriginal": "Exhibidor de plumillas",
    "nombre": "Exhibidor de Plumillas Maximum para Punto de Venta",
    "descripcion": "",
    "image": "imgproductos/creativo_99.jpeg",
    "alt": "Exhibidor de Plumillas Maximum para Punto de Venta",
    "status": "hidden",
    "slug": "exhibidor-de-plumillas-maximum-para-punto-de-venta",
    "category": "Accesorios",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 100,
    "numero": 100,
    "nombreOriginal": "Agua Químicamente Pura AQP-1QG",
    "nombre": "Agua Químicamente Pura AQP-1QG 1/4 de Galón",
    "descripcion": "",
    "image": "imgproductos/creativo_100.jpg",
    "alt": "Agua Químicamente Pura AQP-1QG 1/4 de Galón",
    "status": "hidden",
    "slug": "agua-qumicamente-pura-aqp-1qg-14-de-galn",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 101,
    "numero": 101,
    "nombreOriginal": "Antifreeze & Coolant 1QT",
    "nombre": "Refrigerante Anticongelante Antifreeze & Coolant 50% 1 Qt",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_101.png",
    "alt": "Refrigerante Anticongelante Antifreeze & Coolant 50% 1 Qt",
    "status": "valid",
    "slug": "refrigerante-anticongelante-antifreeze-coolant-50-1-qt",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA COMPLETA DE 50_  11.pdf"
  },
  {
    "id": 102,
    "numero": 102,
    "nombreOriginal": "Antifreeze & Coolant balde",
    "nombre": "Refrigerante Anticongelante Antifreeze & Coolant 50% 5 Galones",
    "descripcion": "",
    "image": "imgproductos/creativo_102.png",
    "alt": "Refrigerante Anticongelante Antifreeze & Coolant 50% 5 Galones",
    "status": "hidden",
    "slug": "refrigerante-anticongelante-antifreeze-coolant-50-5-galones",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 103,
    "numero": 103,
    "nombreOriginal": "Plumillas traseras",
    "nombre": "Plumillas Traseras Maximum",
    "descripcion": "",
    "image": "imgproductos/destacado-plumillas.jpg",
    "alt": "Plumillas Traseras Maximum",
    "status": "valid",
    "slug": "plumillas-traseras-maximum",
    "category": "Carcare",
    "featured": true,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 104,
    "numero": 104,
    "nombreOriginal": "Silicona Premium colores",
    "nombre": "Silicona Premium para Empaquetadura 75 g",
    "descripcion": "",
    "image": "imgproductos/creativo_104.png",
    "alt": "Silicona Premium para Empaquetadura 75 g",
    "status": "hidden",
    "slug": "silicona-premium-para-empaquetadura-75-g",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 105,
    "numero": 105,
    "nombreOriginal": "MX-40D Anti Rust Oil",
    "nombre": "Aceite Aflojatodo MX-40D Anti Rust Oil",
    "descripcion": "",
    "image": "imgproductos/destacado-aflojatodo.jpg",
    "alt": "Aceite Aflojatodo MX-40D Anti Rust Oil",
    "status": "valid",
    "slug": "aceite-aflojatodo-mx-40d-anti-rust-oil",
    "category": "Químicos de Taller",
    "featured": true,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 106,
    "numero": 106,
    "nombreOriginal": "Motor Cool 1 galón",
    "nombre": "Motor Cool Refrigerante y Anticongelante 60% 1 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_106.jpg",
    "alt": "Motor Cool Refrigerante y Anticongelante 60% 1 Galón",
    "status": "valid",
    "slug": "motor-cool-refrigerante-y-anticongelante-60-1-galn",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE 60_ MAXIMUM (4).pdf"
  },
  {
    "id": 107,
    "numero": 107,
    "nombreOriginal": "Repelente de Agua",
    "nombre": "Repelente de Agua para Parabrisas",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_107.png",
    "alt": "Repelente de Agua para Parabrisas",
    "status": "valid",
    "slug": "repelente-de-agua-para-parabrisas",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 108,
    "numero": 108,
    "nombreOriginal": "Tyre Shine",
    "nombre": "Renovador de Llantas Tyre Shine 500 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_108.png",
    "alt": "Renovador de Llantas Tyre Shine 500 ml",
    "status": "valid",
    "slug": "renovador-de-llantas-tyre-shine-500-ml",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 110,
    "numero": 110,
    "nombreOriginal": "Engine Surface Cleaner",
    "nombre": "Engine Surface Cleaner Desengrasante para Motor 395 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_110.png",
    "alt": "Engine Surface Cleaner Desengrasante para Motor 395 ml",
    "status": "valid",
    "slug": "engine-surface-cleaner-desengrasante-para-motor-395-ml",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 111,
    "numero": 111,
    "nombreOriginal": "Creativo Motor Cool 55%",
    "nombre": "Creativo Motor Cool 55% Aditivado para Todo Tipo de Vehículo",
    "descripcion": "",
    "image": "imgproductos/creativo_111.jpeg",
    "alt": "Creativo Motor Cool 55% Aditivado para Todo Tipo de Vehículo",
    "status": "hidden",
    "slug": "creativo-motor-cool-55-aditivado-para-todo-tipo-de-vehculo",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 112,
    "numero": 112,
    "nombreOriginal": "Agua Químicamente Pura 1 galón",
    "nombre": "Agua Químicamente Pura AQP 1 Galón",
    "descripcion": "",
    "image": "imgproductos/creativo_112.jpg",
    "alt": "Agua Químicamente Pura AQP 1 Galón",
    "status": "hidden",
    "slug": "agua-qumicamente-pura-aqp-1-galn",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 113,
    "numero": 113,
    "nombreOriginal": "Antiempañante",
    "nombre": "Spray Antiempañante para Vidrios y Espejos",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_113.png",
    "alt": "Spray Antiempañante para Vidrios y Espejos",
    "status": "valid",
    "slug": "spray-antiempaante-para-vidrios-y-espejos",
    "category": "Otros",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 114,
    "numero": 114,
    "nombreOriginal": "Creativo DOT4",
    "nombre": "Creativo Líquido de Frenos DOT4 Ultra 230°C",
    "descripcion": "",
    "image": "imgproductos/creativo_114.jpeg",
    "alt": "Creativo Líquido de Frenos DOT4 Ultra 230°C",
    "status": "hidden",
    "slug": "creativo-lquido-de-frenos-dot4-ultra-230c",
    "category": "Frenos",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 115,
    "numero": 115,
    "nombreOriginal": "Agua para baterías y radiadores",
    "nombre": "Agua Desionizada y Desmineralizada para Baterías y Radiadores",
    "descripcion": "",
    "image": "imgproductos/creativo_115.jpg",
    "alt": "Agua Desionizada y Desmineralizada para Baterías y Radiadores",
    "status": "hidden",
    "slug": "agua-desionizada-y-desmineralizada-para-bateras-y-radiadores",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 116,
    "numero": 116,
    "nombreOriginal": "DOT3",
    "nombre": "Líquido de Frenos DOT3 Ultra 354 ml",
    "descripcion": "",
    "image": "imgproductos/creativo_116.png",
    "alt": "Líquido de Frenos DOT3 Ultra 354 ml",
    "status": "hidden",
    "slug": "lquido-de-frenos-dot3-ultra-354-ml",
    "category": "Frenos",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 117,
    "numero": 117,
    "nombreOriginal": "Brake Cleaner",
    "nombre": "Brake Cleaner Limpiador Profesional para Sistema de Frenos 500 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_117.png",
    "alt": "Brake Cleaner Limpiador Profesional para Sistema de Frenos 500 ml",
    "status": "valid",
    "slug": "brake-cleaner-limpiador-profesional-para-sistema-de-frenos-500-ml",
    "category": "Frenos",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 118,
    "numero": 118,
    "nombreOriginal": "Creativo Ultra Black y Grey Force",
    "nombre": "Creativo Silicona para Empaquetadura Ultra Black y Grey Force 85 g",
    "descripcion": "",
    "image": "imgproductos/creativo_118.jpg",
    "alt": "Creativo Silicona para Empaquetadura Ultra Black y Grey Force 85 g",
    "status": "hidden",
    "slug": "creativo-silicona-para-empaquetadura-ultra-black-y-grey-force-85-g",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA SILICONA PARA EMPAQUETADURA, GREY FORCE - ULTRA BLACK. (6)"
  },
  {
    "id": 119,
    "numero": 119,
    "nombreOriginal": "Agua Químicamente Pura batería/radiador",
    "nombre": "Agua Químicamente Pura para Baterías, Radiadores y Uso Industrial",
    "descripcion": "",
    "image": "imgproductos/creativo_119.png",
    "alt": "Agua Químicamente Pura para Baterías, Radiadores y Uso Industrial",
    "status": "hidden",
    "slug": "agua-qumicamente-pura-para-bateras-radiadores-y-uso-industrial",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 120,
    "numero": 120,
    "nombreOriginal": "Siliconax Auto Brillo",
    "nombre": "SILICONAX Auto Brillo Silicon Restaurador y Protector 285 gr",
    "descripcion": "",
    "image": "imgproductos/destacado-siliconax-autobrillo.jpg",
    "alt": "SILICONAX Auto Brillo Silicon Restaurador y Protector 285 gr",
    "status": "valid",
    "slug": "siliconax-auto-brillo-silicon-restaurador-285-gr",
    "category": "Carcare",
    "featured": true,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 121,
    "numero": 121,
    "nombreOriginal": "Bouquet ASH",
    "nombre": "Bouquet ASH Ambientador Orgánico Maximum 46 gr",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_121.png",
    "alt": "Bouquet ASH Ambientador Orgánico Maximum 46 gr",
    "status": "valid",
    "slug": "bouquet-ash-ambientador-organico-46-gr",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 122,
    "numero": 122,
    "nombreOriginal": "Catalytic System Ultra-Clean S300",
    "nombre": "Catalytic System Ultra-Clean S300 Limpieza Catalítica 300 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_122.png",
    "alt": "Catalytic System Ultra-Clean S300 Limpieza Catalítica 300 ml",
    "status": "valid",
    "slug": "catalytic-system-ultra-clean-s300-300-ml",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 123,
    "numero": 123,
    "nombreOriginal": "Engine Flush Advanced F300",
    "nombre": "Engine Flush Advanced F300 Restauración Motor 300 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_123.png",
    "alt": "Engine Flush Advanced F300 Restauración Motor 300 ml",
    "status": "valid",
    "slug": "engine-flush-advanced-f300-300-ml",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 124,
    "numero": 124,
    "nombreOriginal": "Extreme Under Coating GA500",
    "nombre": "Extreme Under Coating GA500 Blindaje Automotriz Anti-Gravilla",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_124.png",
    "alt": "Extreme Under Coating GA500 Blindaje Automotriz Anti-Gravilla",
    "status": "valid",
    "slug": "extreme-under-coating-ga500-blindaje-automotriz",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 125,
    "numero": 125,
    "nombreOriginal": "Spray Zinc Oxid Free",
    "nombre": "Spray Zinc Oxid Free Protección Galvanoplástica Profesional 400 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_125.png",
    "alt": "Spray Zinc Oxid Free Protección Galvanoplástica Profesional 400 ml",
    "status": "valid",
    "slug": "spray-zinc-oxid-free-400-ml",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 126,
    "numero": 126,
    "nombreOriginal": "Siliconax Excelencia Premium",
    "nombre": "Siliconax Excelencia Premium Silicona Multi Superficies 350 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_126.png",
    "alt": "Siliconax Excelencia Premium Silicona Multi Superficies 350 ml",
    "status": "valid",
    "slug": "siliconax-excelencia-premium-350-ml",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 127,
    "numero": 127,
    "nombreOriginal": "Brake Fluid Liquid Tester HT662",
    "nombre": "Brake Fluid Liquid Tester HT662 Probador de Líquido de Frenos",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_127.png",
    "alt": "Brake Fluid Liquid Tester HT662 Probador de Líquido de Frenos",
    "status": "valid",
    "slug": "brake-fluid-liquid-tester-ht662",
    "category": "Accesorios",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 128,
    "numero": 128,
    "nombreOriginal": "Brake Fluid Liquid Tester Digital",
    "nombre": "Brake Fluid Liquid Tester Digital Probador de Líquido de Frenos",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_128.png",
    "alt": "Brake Fluid Liquid Tester Digital Probador de Líquido de Frenos",
    "status": "valid",
    "slug": "brake-fluid-liquid-tester-digital",
    "category": "Accesorios",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 129,
    "numero": 129,
    "nombreOriginal": "Kit Diagnóstico Sistema de Refrigeración",
    "nombre": "Kit Profesional de Diagnóstico para Sistema de Refrigeración",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_129.png",
    "alt": "Kit Profesional de Diagnóstico para Sistema de Refrigeración",
    "status": "valid",
    "slug": "kit-profesional-diagnostico-sistema-refrigeracion",
    "category": "Accesorios",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 130,
    "numero": 130,
    "nombreOriginal": "Antifreeze & Coolant IBC 1000L",
    "nombre": "Refrigerante Antifreeze & Coolant 50% IBC 1000 Litros",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_130.png",
    "alt": "Refrigerante Antifreeze & Coolant 50% IBC 1000 Litros",
    "status": "valid",
    "slug": "refrigerante-antifreeze-coolant-50-ibc-1000-litros",
    "category": "Presentaciones",
    "featured": false,
    "orderPriority": 1,
    "pdf": null
  },
  {
    "id": 131,
    "numero": 131,
    "nombreOriginal": "Antifreeze & Coolant Balde 5 Galones Negro",
    "nombre": "Refrigerante Antifreeze & Coolant 50% Balde 5 Galones",
    "descripcion": "",
    "image": "imgproductos/nuevos/balde_ac50_rojo.png",
    "alt": "Refrigerante Antifreeze & Coolant 50% Balde 5 Galones",
    "status": "valid",
    "slug": "refrigerante-antifreeze-coolant-50-balde-5-galones-negro",
    "category": "Presentaciones",
    "featured": false,
    "orderPriority": 1,
    "pdf": null
  }
];
