window.MAXIMUM_PRODUCTS = [
  {
    "id": 1,
    "numero": 1,
    "nombreOriginal": "Motor Cool 60%",
    "nombre": "Refrigerante Motor Cool 60% para GNV/GLP",
    "descripcion": "",
    "image": "imgproductos/creativo_1.jpeg",
    "alt": "Refrigerante Motor Cool 60% para GNV/GLP",
    "status": "hidden",
    "slug": "refrigerante-motor-cool-60-para-gnvglp",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE 60_ MAXIMUM (4).pdf"
  },
  {
    "id": 2,
    "numero": 2,
    "nombreOriginal": "Motor Cool HD Heavy Duty Vehículos Europeos",
    "nombre": "Refrigerante Maximum Motor Cool HD OAT 55/45 Turquesa para Vehículos Europeos",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_2.jpg",
    "alt": "Refrigerante Maximum Motor Cool HD OAT 55/45 Turquesa para Vehículos Europeos",
    "status": "valid",
    "slug": "refrigerante-motor-cool-hd-55-para-vehculos-europeos",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 30,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA COMPLETA DE 55_ NOAT - NITRITO MAXIMUM 3.pdf"
  },
  {
    "id": 3,
    "numero": 3,
    "nombreOriginal": "Antifreeze & Coolant 50%",
    "nombre": "Refrigerante Antifreeze & Coolant 50% para Vehículos Asiáticos",
    "descripcion": "",
    "image": "imgproductos/creativo_3.png",
    "alt": "Refrigerante Antifreeze & Coolant 50% para Vehículos Asiáticos",
    "status": "hidden",
    "slug": "refrigerante-antifreeze-coolant-50-para-vehculos-asiticos",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA COMPLETA DE 50_  11.pdf"
  },
  {
    "id": 4,
    "numero": 4,
    "nombreOriginal": "Trion",
    "nombre": "Silicona Negra para Empaquetadura Premium Maximum Trion – 85 g",
    "descripcion": "",
    "image": "imgproductos/nuevos/taller_trion_silicona.png",
    "alt": "Silicona Negra para Empaquetadura Premium Maximum Trion – 85 g",
    "status": "valid",
    "slug": "silicona-premium-trion-343c",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 450,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA Tecnica SILICONA PARA EMPAQUETADURA TRION MAXIMUM_17.pdf"
  },
  {
    "id": 5,
    "numero": 5,
    "nombreOriginal": "Agua Químicamente Pura",
    "nombre": "Agua Químicamente Pura Desionizada",
    "descripcion": "",
    "image": "imgproductos/creativo_5.jpg",
    "alt": "Agua Químicamente Pura Desionizada",
    "status": "hidden",
    "slug": "agua-qumicamente-pura-desionizada",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 1,
    "pdf": null
  },
  {
    "id": 6,
    "numero": 6,
    "nombreOriginal": "Grasa de Cadena Multipropósito",
    "nombre": "Grasa de Cadena Multipropósito con Lithium Grease",
    "descripcion": "",
    "image": "imgproductos/nuevos/grasa_cadena_spray.png",
    "alt": "Grasa de Cadena Multipropósito con Lithium Grease",
    "status": "hidden",
    "slug": "grasa-de-cadena-multipropsito-con-lithium-grease",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 410,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA MULTIPROPOSITO (5).pdf"
  },
  {
    "id": 7,
    "numero": 7,
    "nombreOriginal": "Gralimax Complejo de Litio",
    "nombre": "Grasa de Complejo de Litio Multipropósito Maximum Gralimax EP3 Azul 300°C – 1 kg",
    "descripcion": "",
    "image": "imgproductos/nuevos/grasa-gralimax-ep3-azul-1kg.png",
    "alt": "Grasa de Complejo de Litio Multipropósito Maximum Gralimax EP3 Azul 300°C – 1 kg",
    "status": "valid",
    "slug": "grasa-gralimax-complejo-de-litio-nlgi-3-ep3",
    "category": "Grasas",
    "featured": true,
    "orderPriority": 370,
    "pdf": null
  },
  {
    "id": 8,
    "numero": 8,
    "nombreOriginal": "Xtrem 5.0",
    "nombre": "Refrigerante Maximum XTREM 5.0 Rojo Reflex para Motos – 1/4 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_8.jpg",
    "alt": "Refrigerante Maximum XTREM 5.0 Rojo Reflex para Motos – 1/4 Galón",
    "status": "valid",
    "slug": "refrigerante-xtrem-50-para-motos",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 260, "imgZoom": true,
    "pdf": null
  },
  {
    "id": 9,
    "numero": 9,
    "nombreOriginal": "Stop Frenomax DOT4",
    "nombre": "Líquido para Frenos Frenomax DOT 4",
    "descripcion": "",
    "image": "imgproductos/creativo_9.png",
    "alt": "Líquido para Frenos Frenomax DOT 4",
    "status": "hidden",
    "slug": "lquido-para-frenos-frenomax-dot-4",
    "category": "Frenos",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 10,
    "numero": 10,
    "nombreOriginal": "Ultra Black / Grey Force",
    "nombre": "Silicona para Empaquetadura Ultra Black / Grey Force",
    "descripcion": "",
    "image": "imgproductos/creativo_10.jpeg",
    "alt": "Silicona para Empaquetadura Ultra Black / Grey Force",
    "status": "hidden",
    "slug": "silicona-para-empaquetadura-ultra-black-grey-force",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 1,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA SILICONA PARA EMPAQUETADURA, GREY FORCE - ULTRA BLACK. (6)"
  },
  {
    "id": 11,
    "numero": 11,
    "nombreOriginal": "Antifreeze & Coolant 33%",
    "nombre": "Refrigerante Maximum Antifreeze & Coolant OAT 33% Verde Reflex – 1 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_11.jpg",
    "alt": "Refrigerante Maximum Antifreeze & Coolant OAT 33% Verde Reflex – 1 Galón",
    "status": "valid",
    "slug": "refrigerante-antifreeze-coolant-33-verde",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 140,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE 33_ MAXIMUM_1.pdf"
  },
  {
    "id": 12,
    "numero": 12,
    "nombreOriginal": "Gralimax Grasa de Lithium EP2",
    "nombre": "Grasa Gralimax de Litio Multipropósito 200°C",
    "descripcion": "",
    "image": "imgproductos/creativo_12.png",
    "alt": "Grasa Gralimax de Litio Multipropósito 200°C",
    "status": "hidden",
    "slug": "grasa-gralimax-de-litio-multipropsito-200c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA MULTIPROPOSITO (5).pdf"
  },
  {
    "id": 13,
    "numero": 13,
    "nombreOriginal": "Estado Zero",
    "nombre": "Limpia Contactos Electrónicos Estado Zero",
    "descripcion": "",
    "image": "imgproductos/creativo_13.jpeg",
    "alt": "Limpia Contactos Electrónicos Estado Zero",
    "status": "hidden",
    "slug": "limpia-contactos-electrnicos-estado-zero",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE LIMPIACONTACTOS ESTADO ZERO(8).pdf"
  },
  {
    "id": 14,
    "numero": 14,
    "nombreOriginal": "Antifreeze & Coolant 33%",
    "nombre": "Refrigerante Maximum Antifreeze & Coolant OAT 33% Rojo Reflex – 1 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_14.jpg",
    "alt": "Refrigerante Maximum Antifreeze & Coolant OAT 33% Rojo Reflex – 1 Galón",
    "status": "valid",
    "slug": "refrigerante-antifreeze-coolant-33-rojo",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 110,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE 33_ MAXIMUM_1.pdf"
  },
  {
    "id": 15,
    "numero": 15,
    "nombreOriginal": "Gralimax Grasa de Lithium Multipropósito",
    "nombre": "Grasa Gralimax de Litio Multipropósito 200°C",
    "descripcion": "",
    "image": "imgproductos/creativo_15.png",
    "alt": "Grasa Gralimax de Litio Multipropósito 200°C",
    "status": "hidden",
    "slug": "grasa-gralimax-de-litio-multipropsito-200c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA MULTIPROPOSITO (5).pdf"
  },
  {
    "id": 16,
    "numero": 16,
    "nombreOriginal": "Carbuchock Cleaner",
    "nombre": "Limpiador de Carburador Carbuchock Cleaner",
    "descripcion": "",
    "image": "imgproductos/creativo_16.jpeg",
    "alt": "Limpiador de Carburador Carbuchock Cleaner",
    "status": "hidden",
    "slug": "limpiador-de-carburador-carbuchock-cleaner",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA LIMPIADOR DE CARBURADOR (12).pdf"
  },
  {
    "id": 17,
    "numero": 17,
    "nombreOriginal": "Refrigerante para Radiador Ice Blue",
    "nombre": "Refrigerante para Motos Maximum ICE Blue No Contiene Etilenglicol – 1/4 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_17.jpg",
    "alt": "Refrigerante para Motos Maximum ICE Blue No Contiene Etilenglicol – 1/4 Galón",
    "status": "valid",
    "slug": "refrigerante-para-radiador-ice-blue-para-motos",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 270, "imgZoom": true,
    "pdf": "FICHAS TECNICAS MAXIMUM/ice blue ficha completa.pdf"
  },
  {
    "id": 18,
    "numero": 18,
    "nombreOriginal": "Nano Coating",
    "nombre": "Protector de Pintura Maximum Nano Coating – 200 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/taller_nano_coating.png",
    "alt": "Protector de Pintura Maximum Nano Coating – 200 ml",
    "status": "valid",
    "slug": "nano-coating-proteccin-total",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 570,
    "pdf": null
  },
  {
    "id": 19,
    "numero": 19,
    "nombreOriginal": "Stop DOT4 Ultra",
    "nombre": "Líquido de Frenos Stop DOT 4 Ultra",
    "descripcion": "",
    "image": "imgproductos/creativo_19.jpeg",
    "alt": "Líquido de Frenos Stop DOT 4 Ultra",
    "status": "hidden",
    "slug": "lquido-de-frenos-stop-dot-4-ultra",
    "category": "Frenos",
    "featured": false,
    "orderPriority": 1,
    "pdf": null
  },
  {
    "id": 20,
    "numero": 20,
    "nombreOriginal": "Motor HD Cool Heavy Duty Diésel",
    "nombre": "Refrigerante Maximum Motor Cool HD Diésel 55/45 Rojo Reflex con OAT + Nitrito – 1 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_20.jpg",
    "alt": "Refrigerante Maximum Motor Cool HD Diésel 55/45 Rojo Reflex con OAT + Nitrito – 1 Galón",
    "status": "valid",
    "slug": "refrigerante-motor-cool-hd-disel-55",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 90,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA COMPLETA DE 55_ NOAT - NITRITO MAXIMUM 3.pdf"
  },
  {
    "id": 21,
    "numero": 21,
    "nombreOriginal": "Shampoo High Eficiency",
    "nombre": "Shampoo con Cera Maximum High Efficiency – 1 Litro",
    "descripcion": "",
    "image": "imgproductos/nuevos/carcare_shampoo_1lt.png",
    "alt": "Shampoo con Cera Maximum High Efficiency – 1 Litro",
    "status": "valid",
    "slug": "shampoo-para-auto-high-eficiency-1-lt",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 610,
    "pdf": null
  },
  {
    "id": 22,
    "numero": 22,
    "nombreOriginal": "Motor Cool GNV/GLP",
    "nombre": "Refrigerante Motor Cool para GNV/GLP 60%",
    "descripcion": "",
    "image": "imgproductos/creativo_22.jpeg",
    "alt": "Refrigerante Motor Cool para GNV/GLP 60%",
    "status": "hidden",
    "slug": "refrigerante-motor-cool-para-gnvglp-60",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 23,
    "numero": 23,
    "nombreOriginal": "Refrigerante para Radiador Ice Blue",
    "nombre": "Refrigerante Maximum ICE Blue para Radiador – 1 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_23.jpg",
    "alt": "Refrigerante Maximum ICE Blue para Radiador – 1 Galón",
    "status": "valid",
    "slug": "refrigerante-para-radiador-ice-blue-1-galn",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 180,
    "pdf": "FICHAS TECNICAS MAXIMUM/ice blue ficha completa.pdf"
  },
  {
    "id": 24,
    "numero": 24,
    "nombreOriginal": "Car Wax Scratch Out",
    "nombre": "Removedor de Rayones Car Wax Scratch Out",
    "descripcion": "",
    "image": "imgproductos/nuevos/taller_car_wax_scratch_out.png",
    "alt": "Removedor de Rayones Car Wax Scratch Out",
    "status": "valid",
    "slug": "removedor-de-rayones-car-wax-scratch-out",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 650,
    "pdf": null
  },
  {
    "id": 25,
    "numero": 25,
    "nombreOriginal": "Agua Químicamente Pura",
    "nombre": "Agua Químicamente Pura Desionizada y Desmineralizada",
    "descripcion": "",
    "image": "imgproductos/creativo_25.jpg",
    "alt": "Agua Químicamente Pura Desionizada y Desmineralizada",
    "status": "hidden",
    "slug": "agua-qumicamente-pura-desionizada-y-desmineralizada",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 26,
    "numero": 26,
    "nombreOriginal": "Limpia Parabrisas",
    "nombre": "Limpia Parabrisas Concentrado 1:100",
    "descripcion": "",
    "image": "imgproductos/creativo_26.png",
    "alt": "Limpia Parabrisas Concentrado 1:100",
    "status": "hidden",
    "slug": "limpia-parabrisas-concentrado-1100",
    "category": "Otros",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 27,
    "numero": 27,
    "nombreOriginal": "Antifreeze & Coolant 50%",
    "nombre": "Refrigerante Maximum Antifreeze & Coolant OAT 50% Rojo Reflex – 1 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_27.jpg",
    "alt": "Refrigerante Maximum Antifreeze & Coolant OAT 50% Rojo Reflex – 1 Galón",
    "status": "valid",
    "slug": "refrigerante-antifreeze-coolant-50-rojo",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 120,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA COMPLETA DE 50_  11.pdf"
  },
  {
    "id": 28,
    "numero": 28,
    "nombreOriginal": "Gralimax Grasa de Lithium EP2",
    "nombre": "Grasa de Litio Multipropósito con Grafito y Molibdeno Maximum Gralimax EP2 200°C",
    "descripcion": "",
    "image": "imgproductos/nuevos/grasa-gralimax-ep2-molibdeno.png",
    "alt": "Grasa de Litio Multipropósito con Grafito y Molibdeno Maximum Gralimax EP2 200°C",
    "status": "valid",
    "slug": "grasa-gralimax-de-litio-ep2-con-molibdeno-y-grafito-200c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 390,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA GRAFITO (6).pdf"
  },
  {
    "id": 29,
    "numero": 29,
    "nombreOriginal": "Motor HD Cool Heavy Duty Vehículos Europeos Violet",
    "nombre": "Refrigerante Maximum Motor Cool HD OAT 55/45 Púrpura para Vehículos Europeos",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_29.jpg",
    "alt": "Refrigerante Maximum Motor Cool HD OAT 55/45 Púrpura para Vehículos Europeos",
    "status": "valid",
    "slug": "refrigerante-motor-cool-hd-vehculos-europeos-violet-55",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 40,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA COMPLETA DE 55_ NOAT - NITRITO MAXIMUM 3.pdf"
  },
  {
    "id": 30,
    "numero": 30,
    "nombreOriginal": "Gralimax Grasa de Lithium H3",
    "nombre": "Grasa de Litio Alta Temperatura Maximum Gralimax H3 Amarilla 260°C – 1 kg",
    "descripcion": "",
    "image": "imgproductos/nuevos/grasa-gralimax-h3-amarilla-1kg.png",
    "alt": "Grasa de Litio Alta Temperatura Maximum Gralimax H3 Amarilla 260°C – 1 kg",
    "status": "valid",
    "slug": "grasa-gralimax-de-litio-h3-200c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 380,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA H3(7).pdf"
  },
  {
    "id": 31,
    "numero": 31,
    "nombreOriginal": "Potencia Estable",
    "nombre": "Creativo Potencia Estable Antifreeze & Coolant 50%",
    "descripcion": "",
    "image": "imgproductos/creativo_31.jpeg",
    "alt": "Creativo Potencia Estable Antifreeze & Coolant 50%",
    "status": "hidden",
    "slug": "creativo-potencia-estable-antifreeze-coolant-50",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 32,
    "numero": 32,
    "nombreOriginal": "Ice Green Taxi Fresh",
    "nombre": "Refrigerante Maximum ICE Green para Radiador – 1 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_32.jpg",
    "alt": "Refrigerante Maximum ICE Green para Radiador – 1 Galón",
    "status": "valid",
    "slug": "refrigerante-para-radiador-ice-green-taxi-fresh-1-galn",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 170,
    "pdf": "FICHAS TECNICAS MAXIMUM/ice blue ficha completa.pdf"
  },
  {
    "id": 33,
    "numero": 33,
    "nombreOriginal": "Motor Cool 60%",
    "nombre": "Refrigerante Maximum Motor Cool 60/40 Rojo Reflex para Vehículos GLP/GNV – 1 Litro",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_33.png",
    "alt": "Refrigerante Maximum Motor Cool 60/40 Rojo Reflex para Vehículos GLP/GNV – 1 Litro",
    "status": "hidden",
    "slug": "refrigerante-motor-cool-60-para-gnvglp-1-qt",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 100, "imgZoom": true,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE 60_ MAXIMUM (4).pdf"
  },
  {
    "id": 34,
    "numero": 34,
    "nombreOriginal": "Motor HD Cool Heavy Duty Vehículos Multimarca Amarillo",
    "nombre": "Refrigerante Maximum Motor Cool HD OAT 55/45 Amarillo para Vehículos Multimarca",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_34.jpg",
    "alt": "Refrigerante Maximum Motor Cool HD OAT 55/45 Amarillo para Vehículos Multimarca",
    "status": "valid",
    "slug": "refrigerante-motor-hd-cool-heavy-duty-vehculos-multimarca-amarillo-55",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 80,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA COMPLETA DE 55_ OEM , 2026.pdf"
  },
  {
    "id": 35,
    "numero": 35,
    "nombreOriginal": "Gralimax Grasa de Lithium EP2",
    "nombre": "Grasa de Litio Multipropósito Maximum Gralimax EP2 Amarilla 200°C – 1 kg",
    "descripcion": "",
    "image": "imgproductos/nuevos/grasa-gralimax-ep2-amarilla-1kg.png",
    "alt": "Grasa de Litio Multipropósito Maximum Gralimax EP2 Amarilla 200°C – 1 kg",
    "status": "hidden",
    "slug": "grasa-gralimax-de-litio-ep2-nlgi-2-multipropsito-200c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 400,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA MULTIPROPOSITO (5).pdf"
  },
  {
    "id": 36,
    "numero": 36,
    "nombreOriginal": "Motor Cool 60%",
    "nombre": "Refrigerante Maximum Motor Cool 60/40 Rojo Reflex para Vehículos GLP/GNV",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_36.png",
    "alt": "Refrigerante Maximum Motor Cool 60/40 Rojo Reflex para Vehículos GLP/GNV",
    "status": "valid",
    "slug": "refrigerante-motor-cool-60-para-gnvglp-1-galn",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 100,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE 60_ MAXIMUM (4).pdf"
  },
  {
    "id": 37,
    "numero": 37,
    "nombreOriginal": "Gralimax Grasa de Lithium H3",
    "nombre": "Grasa Gralimax de Litio H3 260°C",
    "descripcion": "",
    "image": "imgproductos/creativo_37.png",
    "alt": "Grasa Gralimax de Litio H3 260°C",
    "status": "hidden",
    "slug": "grasa-gralimax-de-litio-h3-260c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA H3(7).pdf"
  },
  {
    "id": 38,
    "numero": 38,
    "nombreOriginal": "Shampoo Super Concentrado Brillo Cerámico",
    "nombre": "Shampoo Superconcentrado Brillo Cerámico Maximum – 19 Litros",
    "descripcion": "",
    "image": "imgproductos/nuevos/carcare_shampoo_5gal.jpg",
    "alt": "Shampoo Superconcentrado Brillo Cerámico Maximum – 19 Litros",
    "status": "valid",
    "slug": "shampoo-super-concentrado-brillo-cermico-5-galones",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 630,
    "pdf": null
  },
  {
    "id": 39,
    "numero": 39,
    "nombreOriginal": "Antifreeze & Coolant 33%",
    "nombre": "Refrigerante Maximum Antifreeze & Coolant OAT 33% Rojo Reflex – 1 Galón 1 Galón",
    "descripcion": "",
    "image": "imgproductos/creativo_39.png",
    "alt": "Refrigerante Maximum Antifreeze & Coolant OAT 33% Rojo Reflex – 1 Galón 1 Galón",
    "status": "hidden",
    "slug": "refrigerante-antifreeze-coolant-33-rojo-1-galn",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE 33_ MAXIMUM_1.pdf"
  },
  {
    "id": 40,
    "numero": 40,
    "nombreOriginal": "Ice Orange",
    "nombre": "Refrigerante Maximum ICE Orange para Radiador – 1 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_40.jpg",
    "alt": "Refrigerante Maximum ICE Orange para Radiador – 1 Galón",
    "status": "valid",
    "slug": "refrigerante-para-radiador-ice-orange-1-galn",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 220,
    "pdf": "FICHAS TECNICAS MAXIMUM/ice blue ficha completa.pdf"
  },
  {
    "id": 41,
    "numero": 41,
    "nombreOriginal": "Speedy Klean Limpiador Magnético de Ventana",
    "nombre": "Limpiador Magnético de Ventana Speedy Klean",
    "descripcion": "",
    "image": "imgproductos/creativo_41.png",
    "alt": "Limpiador Magnético de Ventana Speedy Klean",
    "status": "hidden",
    "slug": "limpiador-magntico-de-ventana-speedy-klean",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 42,
    "numero": 42,
    "nombreOriginal": "Motor HD Cool Heavy Duty Vehículos Europeos Pink",
    "nombre": "Refrigerante Maximum Motor Cool HD OAT 55/45 Rosado para Vehículos Europeos",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_42.jpg",
    "alt": "Refrigerante Maximum Motor Cool HD OAT 55/45 Rosado para Vehículos Europeos",
    "status": "valid",
    "slug": "refrigerante-motor-hd-cool-heavy-duty-vehculos-europeos-pink-55",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 10,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA COMPLETA DE 55_ NOAT - NITRITO MAXIMUM 3.pdf"
  },
  {
    "id": 43,
    "numero": 43,
    "nombreOriginal": "Gralimax Grasa de Lithium H3",
    "nombre": "Grasa de Litio Alta Temperatura Maximum Gralimax H3 Azul 260°C – 1 kg",
    "descripcion": "",
    "image": "imgproductos/nuevos/grasa-gralimax-h3-azul-1kg.png",
    "alt": "Grasa Gralimax de Litio H3 260°C",
    "status": "valid",
    "slug": "grasa-gralimax-de-litio-h3-260c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 380,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA H3(7).pdf"
  },
  {
    "id": 44,
    "numero": 44,
    "nombreOriginal": "Antifreeze & Coolant 50%",
    "nombre": "Refrigerante Maximum Antifreeze & Coolant OAT 50% Verde Reflex – 1 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_44.jpg",
    "alt": "Refrigerante Maximum Antifreeze & Coolant OAT 50% Verde Reflex – 1 Galón",
    "status": "valid",
    "slug": "refrigerante-antifreeze-coolant-50-verde-1-galn",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 150,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA COMPLETA DE 50_  11.pdf"
  },
  {
    "id": 45,
    "numero": 45,
    "nombreOriginal": "Speedy Klean Mopa Centrífuga 360",
    "nombre": "Mopa Centrífuga 360 Speedy Klean",
    "descripcion": "",
    "image": "imgproductos/creativo_45.png",
    "alt": "Mopa Centrífuga 360 Speedy Klean",
    "status": "hidden",
    "slug": "mopa-centrfuga-360-speedy-klean",
    "category": "Accesorios",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 46,
    "numero": 46,
    "nombreOriginal": "Ice Dark",
    "nombre": "Refrigerante Maximum ICE Dark para Radiador – 1 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_46.jpg",
    "alt": "Refrigerante Maximum ICE Dark para Radiador – 1 Galón",
    "status": "valid",
    "slug": "refrigerante-para-radiador-ice-dark-1-galn",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 200,
    "pdf": "FICHAS TECNICAS MAXIMUM/ice blue ficha completa.pdf"
  },
  {
    "id": 47,
    "numero": 47,
    "nombreOriginal": "Gralimax Grasa de Lithium EP2 Molibdeno Grafito",
    "nombre": "Grasa de Litio Multipropósito con Grafito y Molibdeno Maximum Gralimax EP2 200°C",
    "descripcion": "",
    "image": "imgproductos/nuevos/grasa-gralimax-ep2-molibdeno.png",
    "alt": "Grasa de Litio Multipropósito con Grafito y Molibdeno Maximum Gralimax EP2 200°C",
    "status": "hidden",
    "slug": "grasa-gralimax-de-litio-ep2-con-molibdeno-y-grafito-200c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 30,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA GRAFITO (6).pdf"
  },
  {
    "id": 48,
    "numero": 48,
    "nombreOriginal": "Ice Violet",
    "nombre": "Refrigerante Maximum ICE Violet para Radiador – 1 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_48.jpg",
    "alt": "Refrigerante Maximum ICE Violet para Radiador – 1 Galón",
    "status": "valid",
    "slug": "refrigerante-para-radiador-ice-violet-1-galn",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 210,
    "pdf": "FICHAS TECNICAS MAXIMUM/ice blue ficha completa.pdf"
  },
  {
    "id": 49,
    "numero": 49,
    "nombreOriginal": "Antifreeze & Coolant 50% Balde",
    "nombre": "Balde Heavy Duty – 5 Galones",
    "descripcion": "",
    "image": "imgproductos/nuevos/balde-heavy-duty-5gal.png",
    "alt": "Balde Heavy Duty – 5 Galones",
    "status": "valid",
    "slug": "refrigerante-antifreeze-coolant-50-verde-balde-5-galones",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 120,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA COMPLETA DE 50_  11.pdf"
  },
  {
    "id": 50,
    "numero": 50,
    "nombreOriginal": "Motor HD Cool Heavy Duty Vehículos Americanos Orange",
    "nombre": "Refrigerante Maximum Motor Cool HD OAT 55/45 Naranja para Vehículos Americanos",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_50.jpg",
    "alt": "Refrigerante Maximum Motor Cool HD OAT 55/45 Naranja para Vehículos Americanos",
    "status": "valid",
    "slug": "refrigerante-motor-hd-cool-heavy-duty-vehculos-americanos-orange-55",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 70,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA COMPLETA DE 55_ OEM , 2026.pdf"
  },
  {
    "id": 51,
    "numero": 51,
    "nombreOriginal": "Carbu Chock Cleaner Limpiador de Carburador",
    "nombre": "Limpiador de Carburador y Sistema de Admisión Maximum Carbuchock Plus Limón – 600 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/taller_carbu_chock.png",
    "alt": "Limpiador de Carburador y Sistema de Admisión Maximum Carbuchock Plus Limón – 600 ml",
    "status": "valid",
    "slug": "limpiador-de-carburador-carbu-chock-cleaner-aroma-a-limn",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 340,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA LIMPIADOR DE CARBURADOR (12).pdf"
  },
  {
    "id": 52,
    "numero": 52,
    "nombreOriginal": "Antifreeze & Coolant 17%",
    "nombre": "Refrigerante Maximum Antifreeze & Coolant OAT 17% Verde Reflex – 1 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_52.jpg",
    "alt": "Refrigerante Maximum Antifreeze & Coolant OAT 17% Verde Reflex – 1 Galón",
    "status": "valid",
    "slug": "refrigerante-antifreeze-coolant-17-verde-1-galn",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 130,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE 17_ MAXIMUM_1.pdf"
  },
  {
    "id": 53,
    "numero": 53,
    "nombreOriginal": "Plastic & Leather Renewer",
    "nombre": "Renovador de Plásticos y Cuero Maximum Plastic & Leather Renewer – 30 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/carcare_plastic_leather.png",
    "alt": "Renovador de Plásticos y Cuero Maximum Plastic & Leather Renewer – 30 ml",
    "status": "valid",
    "slug": "renovador-de-plstico-y-cuero-plastic-leather-renewer",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 670,
    "pdf": null
  },
  {
    "id": 54,
    "numero": 54,
    "nombreOriginal": "Máxima Protección",
    "nombre": "Creativo Máxima Protección Antifreeze & Coolant 33%",
    "descripcion": "",
    "image": "imgproductos/creativo_54.jpeg",
    "alt": "Creativo Máxima Protección Antifreeze & Coolant 33%",
    "status": "hidden",
    "slug": "creativo-mxima-proteccin-antifreeze-coolant-33",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 55,
    "numero": 55,
    "nombreOriginal": "EGA964 Etilenglicol Aditivado",
    "nombre": "Refrigerante Concentrado Maximum EGA964 Rojo Reflex 96/4 – 1/4 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_55.jpg",
    "alt": "Refrigerante Concentrado Maximum EGA964 Rojo Reflex 96/4 – 1/4 Galón",
    "status": "valid",
    "slug": "refrigerante-concentrado-ega964-etilenglicol-aditivado-rojo-reflex",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 240,
    "pdf": null
  },
  {
    "id": 56,
    "numero": 56,
    "nombreOriginal": "Trion Premium",
    "nombre": "Silicona Negra para Empaquetadura Premium Maximum Trion – 85 g",
    "descripcion": "",
    "image": "imgproductos/creativo_56.png",
    "alt": "Silicona Negra para Empaquetadura Premium Maximum Trion – 85 g",
    "status": "hidden",
    "slug": "silicona-premium-trion-343c",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA Tecnica SILICONA PARA EMPAQUETADURA TRION MAXIMUM_17.pdf"
  },
  {
    "id": 57,
    "numero": 57,
    "nombreOriginal": "Motor HD Cool Heavy Duty Vehículos Asiáticos Green",
    "nombre": "Refrigerante Maximum Motor Cool HD OAT 55/45 Verde para Vehículos Asiáticos",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_57.jpg",
    "alt": "Refrigerante Maximum Motor Cool HD OAT 55/45 Verde para Vehículos Asiáticos",
    "status": "valid",
    "slug": "refrigerante-motor-hd-cool-heavy-duty-vehculos-asiticos-green-55",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 60,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA COMPLETA DE 55_ OEM , 2026.pdf"
  },
  {
    "id": 58,
    "numero": 58,
    "nombreOriginal": "Protector Total Mate",
    "nombre": "Protector Total Mate para interior y exterior",
    "descripcion": "",
    "image": "imgproductos/creativo_58.png",
    "alt": "Protector Total Mate para interior y exterior",
    "status": "hidden",
    "slug": "protector-total-mate-para-interior-y-exterior",
    "category": "Otros",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 59,
    "numero": 59,
    "nombreOriginal": "Ice Pink",
    "nombre": "Refrigerante Maximum ICE Pink para Radiador – 1 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_59.jpg",
    "alt": "Refrigerante Maximum ICE Pink para Radiador – 1 Galón",
    "status": "valid",
    "slug": "refrigerante-para-radiador-ice-pink-1-galn",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 190,
    "pdf": "FICHAS TECNICAS MAXIMUM/ice blue ficha completa.pdf"
  },
  {
    "id": 60,
    "numero": 60,
    "nombreOriginal": "Gralimax Grasa de Lithium EP2 NLGI2 200°C",
    "nombre": "Grasa de Litio Multipropósito Maximum Gralimax EP2 Amarilla 200°C – 1 kg",
    "descripcion": "",
    "image": "imgproductos/nuevos/grasa-gralimax-ep2-amarilla-1kg.png",
    "alt": "Grasa de Litio Multipropósito Maximum Gralimax EP2 Amarilla 200°C – 1 kg",
    "status": "valid",
    "slug": "grasa-gralimax-de-litio-ep2-nlgi2-200c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 400,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA MULTIPROPOSITO (5).pdf"
  },
  {
    "id": 61,
    "numero": 61,
    "nombreOriginal": "Motor HD Cool Heavy Duty Vehículos Asiáticos Blue",
    "nombre": "Refrigerante Maximum Motor Cool HD OAT 55/45 Azul para Vehículos Asiáticos",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_61.jpg",
    "alt": "Refrigerante Maximum Motor Cool HD OAT 55/45 Azul para Vehículos Asiáticos",
    "status": "valid",
    "slug": "refrigerante-motor-hd-cool-heavy-duty-vehculos-asiticos-blue-55",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 20,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA COMPLETA DE 55_ OEM , 2026.pdf"
  },
  {
    "id": 62,
    "numero": 62,
    "nombreOriginal": "Agua Químicamente Pura",
    "nombre": "Agua Químicamente Pura Maximum Desionizada y Desmineralizada – 1 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/refrig_agua_pura_1gal.jpg",
    "alt": "Agua Químicamente Pura Maximum Desionizada y Desmineralizada – 1 Galón",
    "status": "valid",
    "slug": "agua-qumicamente-pura-desionizada-y-desmineralizada-1-galn-5-litros",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 250,
    "pdf": null
  },
  {
    "id": 63,
    "numero": 63,
    "nombreOriginal": "Ice Blue 5 Galones",
    "nombre": "Refrigerante para Radiador Maximum ICE Industrial No Concentrado – 5 Galones",
    "descripcion": "",
    "image": "imgproductos/nuevos/ice-industrial-no-concentrado-5gal.jpg",
    "alt": "Refrigerante para Radiador Maximum ICE Industrial No Concentrado – 5 Galones",
    "status": "valid",
    "slug": "refrigerante-para-radiador-ice-blue-5-galones",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 180,
    "pdf": "FICHAS TECNICAS MAXIMUM/ice blue ficha completa.pdf"
  },
  {
    "id": 64,
    "numero": 64,
    "nombreOriginal": "Agua Químicamente Pura AQP-1QG",
    "nombre": "Agua Químicamente Pura Maximum Desionizada y Desmineralizada – 1/4 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/refrig_agua_pura_qt.jpg",
    "alt": "Agua Químicamente Pura Maximum Desionizada y Desmineralizada – 1/4 Galón",
    "status": "valid",
    "slug": "agua-qumicamente-pura-aqp-1qg-1-cuarto-de-galn",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 250,
    "pdf": null
  },
  {
    "id": 65,
    "numero": 65,
    "nombreOriginal": "Ice Yellow",
    "nombre": "Refrigerante Maximum ICE Yellow para Radiador – 1 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_65.jpg",
    "alt": "Refrigerante Maximum ICE Yellow para Radiador – 1 Galón",
    "status": "valid",
    "slug": "refrigerante-para-radiador-ice-yellow-1-galn",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 230,
    "pdf": "FICHAS TECNICAS MAXIMUM/ice blue ficha completa.pdf"
  },
  {
    "id": 66,
    "numero": 66,
    "nombreOriginal": "Stop Líquido de Frenos DOT5.1",
    "nombre": "Stop DOT 5.1 Ultra – Líquido de Frenos – 354 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/taller_stop_dot51.png",
    "alt": "Stop DOT 5.1 Ultra – Líquido de Frenos – 354 ml",
    "status": "valid",
    "slug": "lquido-de-frenos-stop-dot51-ultra-354-ml",
    "category": "Frenos",
    "featured": false,
    "orderPriority": 440,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA LIQUIDO DE FRENOS (11).pdf"
  },
  {
    "id": 67,
    "numero": 67,
    "nombreOriginal": "Motor HD Cool Heavy Duty Vehículos Multimarca Rojo",
    "nombre": "Refrigerante Maximum Motor Cool HD OAT 55/45 Rojo para Vehículos Multimarca",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_67.jpg",
    "alt": "Refrigerante Maximum Motor Cool HD OAT 55/45 Rojo para Vehículos Multimarca",
    "status": "valid",
    "slug": "refrigerante-motor-hd-cool-heavy-duty-vehculos-multimarca-rojo-55",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 50,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA COMPLETA DE 55_ OEM , 2026.pdf"
  },
  {
    "id": 68,
    "numero": 68,
    "nombreOriginal": "Motor Cool 5 Galones GLP/GNV",
    "nombre": "Refrigerante Maximum Motor Cool 60/40 Rojo Reflex para Vehículos GLP/GNV – 5 Galones",
    "descripcion": "",
    "image": "imgproductos/nuevos/balde_motorcool_glp.png",
    "alt": "Refrigerante Maximum Motor Cool 60/40 Rojo Reflex para Vehículos GLP/GNV – 5 Galones",
    "status": "valid",
    "slug": "refrigerante-motor-cool-glpgnv-60-5-galones",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 100,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE 60_ MAXIMUM (4).pdf"
  },
  {
    "id": 69,
    "numero": 69,
    "nombreOriginal": "Injector Cleaner Gasolina",
    "nombre": "Injector Cleaner Pro – Limpiador de Inyectores Gasolina y Diésel – 354 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/taller_inyector_cleaner.png",
    "alt": "Injector Cleaner Pro – Limpiador de Inyectores Gasolina y Diésel – 354 ml",
    "status": "valid",
    "slug": "limpiador-de-inyectores-injector-cleaner-gasolina",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 420,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA COMPLETA INYECTORES3.pdf"
  },
  {
    "id": 70,
    "numero": 70,
    "nombreOriginal": "Gralimax Grasa de Lithium EP2 NLGI2 200°C",
    "nombre": "Grasa de Litio Multipropósito Maximum Gralimax EP2 Amarilla 200°C – 1 kg",
    "descripcion": "",
    "image": "imgproductos/creativo_70.png",
    "alt": "Grasa de Litio Multipropósito Maximum Gralimax EP2 Amarilla 200°C – 1 kg",
    "status": "hidden",
    "slug": "grasa-gralimax-de-litio-ep2-nlgi2-200c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 71,
    "numero": 71,
    "nombreOriginal": "Gralimax Grasa de Lithium H3",
    "nombre": "Grasa Gralimax de Litio H3 260°C",
    "descripcion": "",
    "image": "imgproductos/nuevos/grasa-gralimax-h3-amarilla-1kg.png",
    "alt": "Grasa Gralimax de Litio H3 260°C",
    "status": "hidden",
    "slug": "grasa-gralimax-de-litio-h3-260c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 30,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA H3(7).pdf"
  },
  {
    "id": 72,
    "numero": 72,
    "nombreOriginal": "Gralimax Grasa de Lithium H3 Balde",
    "nombre": "Grasa Gralimax de Litio H3 NLGI2 260°C Balde",
    "descripcion": "",
    "image": "imgproductos/creativo_72.png",
    "alt": "Grasa Gralimax de Litio H3 NLGI2 260°C Balde",
    "status": "hidden",
    "slug": "grasa-gralimax-de-litio-h3-nlgi2-260c-balde",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA H3(7).pdf"
  },
  {
    "id": 73,
    "numero": 73,
    "nombreOriginal": "Creativo Ice Aditivados",
    "nombre": "Creativo Línea Ice Aditivados Ecológicos",
    "descripcion": "",
    "image": "imgproductos/creativo_73.jpeg",
    "alt": "Creativo Línea Ice Aditivados Ecológicos",
    "status": "hidden",
    "slug": "creativo-lnea-ice-aditivados-ecolgicos",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 74,
    "numero": 74,
    "nombreOriginal": "Ice Red",
    "nombre": "Refrigerante Maximum ICE Red para Radiador – 1 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_74.jpg",
    "alt": "Refrigerante Maximum ICE Red para Radiador – 1 Galón",
    "status": "valid",
    "slug": "refrigerante-para-radiador-ice-red-1-galn",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 160,
    "pdf": "FICHAS TECNICAS MAXIMUM/ice blue ficha completa.pdf"
  },
  {
    "id": 75,
    "numero": 75,
    "nombreOriginal": "Gralimax Grasa de Lithium H3 Amarillo",
    "nombre": "Grasa de Litio Alta Temperatura Maximum Gralimax H3 Roja 260°C – 1 kg",
    "descripcion": "",
    "image": "imgproductos/nuevos/grasa-gralimax-h3-roja-1kg.png",
    "alt": "Grasa Gralimax de Litio H3 260°C",
    "status": "valid",
    "slug": "grasa-gralimax-de-litio-h3-260c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 380,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA H3(7).pdf"
  },
  {
    "id": 76,
    "numero": 76,
    "nombreOriginal": "Gralimax Grasa de Lithium H3 Balde Azul",
    "nombre": "Grasa Gralimax de Litio H3 NLGI2 260°C Balde",
    "descripcion": "",
    "image": "imgproductos/creativo_76.png",
    "alt": "Grasa Gralimax de Litio H3 NLGI2 260°C Balde",
    "status": "hidden",
    "slug": "grasa-gralimax-de-litio-h3-nlgi2-260c-balde",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA H3(7).pdf"
  },
  {
    "id": 77,
    "numero": 77,
    "nombreOriginal": "Tambor Maximum",
    "nombre": "Cilindro Superior – 55 Galones",
    "descripcion": "",
    "image": "imgproductos/nuevos/cilindro-superior-55gal.png",
    "alt": "Cilindro Superior – 55 Galones",
    "status": "valid",
    "slug": "tambor-maximum-tecnologa-automotriz",
    "category": "Presentaciones",
    "featured": false,
    "orderPriority": 275,
    "pdf": null
  },
  {
    "id": 78,
    "numero": 78,
    "nombreOriginal": "Motor HD Cool Heavy Duty Diesel 5 Galones",
    "nombre": "Refrigerante Maximum Motor Cool HD Diésel 55/45 Rojo Reflex con OAT + Nitrito – 5 Galones",
    "descripcion": "",
    "image": "imgproductos/nuevos/balde_hd_diesel.png",
    "alt": "Refrigerante Maximum Motor Cool HD Diésel 55/45 Rojo Reflex con OAT + Nitrito – 5 Galones",
    "status": "valid",
    "slug": "refrigerante-motor-hd-cool-heavy-duty-diesel-55-5-galones",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 90,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA COMPLETA DE 55_ NOAT - NITRITO MAXIMUM 3.pdf"
  },
  {
    "id": 79,
    "numero": 79,
    "nombreOriginal": "Gralimax Grasa de Lithium Multipropósito Amarillo",
    "nombre": "Grasa Gralimax de Litio Multipropósito 200°C",
    "descripcion": "",
    "image": "imgproductos/nuevos/grasa-gralimax-ep2-amarilla-1kg.png",
    "alt": "Grasa Gralimax de Litio Multipropósito 200°C",
    "status": "hidden",
    "slug": "grasa-gralimax-de-litio-multipropsito-200c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 30,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA MULTIPROPOSITO (5).pdf"
  },
  {
    "id": 80,
    "numero": 80,
    "nombreOriginal": "Gralimax Grasa de Lithium Multipropósito Amarillo",
    "nombre": "Grasa de Litio Multipropósito Maximum Gralimax EP2 Roja 200°C – 1 kg",
    "descripcion": "",
    "image": "imgproductos/nuevos/grasa-gralimax-ep2-roja-1kg.png",
    "alt": "Grasa Gralimax de Litio Multipropósito 200°C",
    "status": "valid",
    "slug": "grasa-gralimax-de-litio-multipropsito-200c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 400,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA MULTIPROPOSITO (5).pdf"
  },
  {
    "id": 81,
    "numero": 81,
    "nombreOriginal": "Gralimax Grasa de Lithium H3",
    "nombre": "Grasa Gralimax de Litio H3 260°C",
    "descripcion": "",
    "image": "imgproductos/nuevos/grasa-gralimax-h3-roja-1kg.png",
    "alt": "Grasa Gralimax de Litio H3 260°C",
    "status": "hidden",
    "slug": "grasa-gralimax-de-litio-h3-260c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 30,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA H3(7).pdf"
  },
  {
    "id": 82,
    "numero": 82,
    "nombreOriginal": "Gralimax Grasa de Lithium Multipropósito Roja",
    "nombre": "Grasa de Litio Multipropósito Maximum Gralimax EP2 Azul 200°C – 1 kg",
    "descripcion": "",
    "image": "imgproductos/nuevos/grasa-gralimax-ep2-azul-1kg.png",
    "alt": "Grasa Gralimax de Litio Multipropósito 200°C",
    "status": "valid",
    "slug": "grasa-gralimax-de-litio-multipropsito-200c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 400,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA MULTIPROPOSITO (5).pdf"
  },
  {
    "id": 83,
    "numero": 83,
    "nombreOriginal": "Gralimax Grasa de Lithium Multipropósito Balde Amarillo",
    "nombre": "Grasa Gralimax de Litio Multipropósito EP2 NLGI2 200°C Balde",
    "descripcion": "",
    "image": "imgproductos/creativo_83.png",
    "alt": "Grasa Gralimax de Litio Multipropósito EP2 NLGI2 200°C Balde",
    "status": "hidden",
    "slug": "grasa-gralimax-de-litio-multipropsito-ep2-nlgi2-200c-balde",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 84,
    "numero": 84,
    "nombreOriginal": "Gralimax Grasa de Lithium H3 Cartucho",
    "nombre": "Cartucho de Grasa Gralimax de Litio H3 260°C",
    "descripcion": "",
    "image": "imgproductos/creativo_84.png",
    "alt": "Cartucho de Grasa Gralimax de Litio H3 260°C",
    "status": "hidden",
    "slug": "cartucho-de-grasa-gralimax-de-litio-h3-260c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA H3(7).pdf"
  },
  {
    "id": 85,
    "numero": 85,
    "nombreOriginal": "Gralimax Grasa de Lithium Multipropósito Cartucho",
    "nombre": "Cartucho de Grasa Gralimax de Litio Multipropósito 200°C",
    "descripcion": "",
    "image": "imgproductos/creativo_85.png",
    "alt": "Cartucho de Grasa Gralimax de Litio Multipropósito 200°C",
    "status": "hidden",
    "slug": "cartucho-de-grasa-gralimax-de-litio-multipropsito-200c",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE GRASA MULTIPROPOSITO (5).pdf"
  },
  {
    "id": 86,
    "numero": 86,
    "nombreOriginal": "Creativo Vehículos Asiáticos Verde OAT",
    "nombre": "Creativo Refrigerante Verde OAT para Vehículos Asiáticos",
    "descripcion": "",
    "image": "imgproductos/creativo_86.jpeg",
    "alt": "Creativo Refrigerante Verde OAT para Vehículos Asiáticos",
    "status": "hidden",
    "slug": "creativo-refrigerante-verde-oat-para-vehculos-asiticos",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 87,
    "numero": 87,
    "nombreOriginal": "Agua Químicamente Pura",
    "nombre": "Agua Químicamente Pura Maximum 5 Litros",
    "descripcion": "",
    "image": "imgproductos/creativo_87.jpg",
    "alt": "Agua Químicamente Pura Maximum 5 Litros",
    "status": "hidden",
    "slug": "agua-qumicamente-pura-maximum-5-litros",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 88,
    "numero": 88,
    "nombreOriginal": "Foam Cleaner Multipurpose",
    "nombre": "Espuma de Limpieza Multiuso Maximum Foam Cleaner – 600 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/carcare_foam_cleaner.png",
    "alt": "Espuma de Limpieza Multiuso Maximum Foam Cleaner – 600 ml",
    "status": "valid",
    "slug": "espuma-limpiadora-multipropsito-foam-cleaner-600-ml",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 590,
    "pdf": null
  },
  {
    "id": 89,
    "numero": 89,
    "nombreOriginal": "Grey Force",
    "nombre": "Silicona Gris para Empaquetadura Maximum Grey Force – 85 g",
    "descripcion": "",
    "image": "imgproductos/nuevos/taller_grey_force.png",
    "alt": "Silicona Gris para Empaquetadura Maximum Grey Force – 85 g",
    "status": "valid",
    "slug": "silicona-para-empaquetadura-grey-force-343c-85-gr",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 460,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA SILICONA PARA EMPAQUETADURA, GREY FORCE - ULTRA BLACK. (6)"
  },
  {
    "id": 90,
    "numero": 90,
    "nombreOriginal": "Ultra Black",
    "nombre": "Silicona Negra para Empaquetadura Maximum Ultra Black – 85 g",
    "descripcion": "",
    "image": "imgproductos/nuevos/taller_ultra_black.png",
    "alt": "Silicona Negra para Empaquetadura Maximum Ultra Black – 85 g",
    "status": "valid",
    "slug": "silicona-para-empaquetadura-ultra-black-343c-85-gr",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 470,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA SILICONA PARA EMPAQUETADURA, GREY FORCE - ULTRA BLACK. (6)"
  },
  {
    "id": 91,
    "numero": 91,
    "nombreOriginal": "Stop DOT4 Ultra",
    "nombre": "Stop DOT 4 Ultra – Líquido de Frenos – 354 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/taller_stop_dot4.png",
    "alt": "Stop DOT 4 Ultra – Líquido de Frenos – 354 ml",
    "status": "valid",
    "slug": "lquido-de-frenos-dot4-ultra-230c-354-ml",
    "category": "Frenos",
    "featured": false,
    "orderPriority": 430,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA LIQUIDO DE FRENOS (11).pdf"
  },
  {
    "id": 92,
    "numero": 92,
    "nombreOriginal": "Estado Zero",
    "nombre": "Limpiador de Contactos Eléctricos Maximum Estado Zero X-Clean – 400 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/taller_estado_zero.png",
    "alt": "Limpiador de Contactos Eléctricos Maximum Estado Zero X-Clean – 400 ml",
    "status": "valid",
    "slug": "limpiacontactos-electrnicos-estado-zero-aroma-limn",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 360,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE LIMPIACONTACTOS ESTADO ZERO(8).pdf"
  },
  {
    "id": 93,
    "numero": 93,
    "nombreOriginal": "Injector Cleaner Diesel Turbo Cargado",
    "nombre": "Limpiador de Inyectores Diesel Turbo Cargado 354 ml",
    "descripcion": "",
    "image": "imgproductos/creativo_93.png",
    "alt": "Limpiador de Inyectores Diesel Turbo Cargado 354 ml",
    "status": "hidden",
    "slug": "limpiador-de-inyectores-diesel-turbo-cargado-354-ml",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 94,
    "numero": 94,
    "nombreOriginal": "Kristal Clean",
    "nombre": "Limpiaparabrisas Maximum Kristal Clean – 1 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/kristal-clean-1galon.png",
    "alt": "Limpiaparabrisas Maximum Kristal Clean – 1 Galón",
    "status": "valid",
    "slug": "limpia-parabrisas-kristal-clean-1-galn",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 550, "imgZoom": true,
    "pdf": null
  },
  {
    "id": 95,
    "numero": 95,
    "nombreOriginal": "Kristal Clean foto real",
    "nombre": "Limpiaparabrisas Maximum Kristal Clean – 1/4 Galón",
    "descripcion": "",
    "image": "imgproductos/nuevos/kristal-clean-cuarto-galon.png",
    "alt": "Limpiaparabrisas Maximum Kristal Clean – 1/4 Galón",
    "status": "valid",
    "slug": "limpia-parabrisas-kristal-clean-1-qt",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 560,
    "pdf": null
  },
  {
    "id": 96,
    "numero": 96,
    "nombreOriginal": "Agua Químicamente Pura foto real",
    "nombre": "Agua Químicamente Pura Maximum Desionizada y Desmineralizada – 1 Qt",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_96.png",
    "alt": "Agua Químicamente Pura Maximum Desionizada y Desmineralizada – 1 Qt",
    "status": "hidden",
    "slug": "agua-qumicamente-pura-maximum-1-qt",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 250, "imgZoom": true,
    "pdf": null
  },
  {
    "id": 97,
    "numero": 97,
    "nombreOriginal": "Kristal Home",
    "nombre": "Limpiavidrios y Limpiaparabrisas Maximum Kristal Home – 650 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/kristal-home-650ml.png",
    "alt": "Limpiavidrios y Limpiaparabrisas Maximum Kristal Home – 650 ml",
    "status": "valid",
    "slug": "limpiavidrios-kristal-home-650-ml",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 540,
    "pdf": null
  },
  {
    "id": 98,
    "numero": 98,
    "nombreOriginal": "Shampoo Brillo Cerámico",
    "nombre": "Shampoo con Cera Maximum High Efficiency – 350 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/carcare_shampoo_350ml.png",
    "alt": "Shampoo con Cera Maximum High Efficiency – 350 ml",
    "status": "valid",
    "slug": "shampoo-sper-concentrado-brillo-cermico-350-ml",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 620,
    "pdf": null
  },
  {
    "id": 99,
    "numero": 99,
    "nombreOriginal": "Exhibidor de plumillas",
    "nombre": "Exhibidor de Plumillas Maximum para Punto de Venta",
    "descripcion": "",
    "image": "imgproductos/creativo_99.jpeg",
    "alt": "Exhibidor de Plumillas Maximum para Punto de Venta",
    "status": "hidden",
    "slug": "exhibidor-de-plumillas-maximum-para-punto-de-venta",
    "category": "Accesorios",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 100,
    "numero": 100,
    "nombreOriginal": "Agua Químicamente Pura AQP-1QG",
    "nombre": "Agua Químicamente Pura AQP-1QG 1/4 de Galón",
    "descripcion": "",
    "image": "imgproductos/creativo_100.jpg",
    "alt": "Agua Químicamente Pura AQP-1QG 1/4 de Galón",
    "status": "hidden",
    "slug": "agua-qumicamente-pura-aqp-1qg-14-de-galn",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 250, "imgZoom": true,
    "pdf": null
  },
  {
    "id": 101,
    "numero": 101,
    "nombreOriginal": "Antifreeze & Coolant 1QT",
    "nombre": "Refrigerante Maximum Antifreeze & Coolant OAT 50% Verde Reflex – 1 Qt",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_101.png",
    "alt": "Refrigerante Maximum Antifreeze & Coolant OAT 50% Verde Reflex – 1 Qt",
    "status": "hidden",
    "slug": "refrigerante-anticongelante-antifreeze-coolant-50-1-qt",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 120,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA COMPLETA DE 50_  11.pdf"
  },
  {
    "id": 102,
    "numero": 102,
    "nombreOriginal": "Antifreeze & Coolant balde",
    "nombre": "Refrigerante Anticongelante Antifreeze & Coolant 50% 5 Galones",
    "descripcion": "",
    "image": "imgproductos/creativo_102.png",
    "alt": "Refrigerante Anticongelante Antifreeze & Coolant 50% 5 Galones",
    "status": "hidden",
    "slug": "refrigerante-anticongelante-antifreeze-coolant-50-5-galones",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 103,
    "numero": 103,
    "nombreOriginal": "Plumillas traseras",
    "nombre": "Plumilla Ergonómica de Silicona Premium Maximum",
    "descripcion": "",
    "image": "imgproductos/nuevos/carcare_plumillas.png",
    "alt": "Plumilla Ergonómica de Silicona Premium Maximum",
    "status": "valid",
    "slug": "plumillas-traseras-maximum",
    "category": "Carcare",
    "featured": true,
    "orderPriority": 600,
    "pdf": null
  },
  {
    "id": 104,
    "numero": 104,
    "nombreOriginal": "Silicona Premium colores",
    "nombre": "Silicona Premium para Empaquetadura 75 g",
    "descripcion": "",
    "image": "imgproductos/creativo_104.png",
    "alt": "Silicona Premium para Empaquetadura 75 g",
    "status": "hidden",
    "slug": "silicona-premium-para-empaquetadura-75-g",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 105,
    "numero": 105,
    "nombreOriginal": "MX-40D Anti Rust Oil",
    "nombre": "Aflojatodo Ultra Penetrante Maximum – 311 g",
    "descripcion": "",
    "image": "imgproductos/nuevos/taller_afloja_todo.png",
    "alt": "Aflojatodo Ultra Penetrante Maximum – 311 g",
    "status": "valid",
    "slug": "aceite-aflojatodo-mx-40d-anti-rust-oil",
    "category": "Químicos de Taller",
    "featured": true,
    "orderPriority": 350,
    "pdf": null
  },
  {
    "id": 106,
    "numero": 106,
    "nombreOriginal": "Motor Cool 1 galón",
    "nombre": "Refrigerante Maximum Motor Cool 60/40 Verde Reflex para Vehículos GLP/GNV",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_106.jpg",
    "alt": "Refrigerante Maximum Motor Cool 60/40 Verde Reflex para Vehículos GLP/GNV",
    "status": "valid",
    "slug": "motor-cool-refrigerante-y-anticongelante-60-1-galn",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 100,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA DE 60_ MAXIMUM (4).pdf"
  },
  {
    "id": 107,
    "numero": 107,
    "nombreOriginal": "Repelente de Agua",
    "nombre": "Repelente de Agua para Vidrios Maximum Glass Water Repellent – 120 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/carcare_repelente_agua.png",
    "alt": "Repelente de Agua para Vidrios Maximum Glass Water Repellent – 120 ml",
    "status": "valid",
    "slug": "repelente-de-agua-para-parabrisas",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 660,
    "pdf": null
  },
  {
    "id": 108,
    "numero": 108,
    "nombreOriginal": "Tyre Shine",
    "nombre": "Abrillantador de Llantas Maximum Tyre Shine – 500 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/carcare_tyre_shine.png",
    "alt": "Abrillantador de Llantas Maximum Tyre Shine – 500 ml",
    "status": "valid",
    "slug": "renovador-de-llantas-tyre-shine-500-ml",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 580,
    "pdf": null
  },
  {
    "id": 110,
    "numero": 110,
    "nombreOriginal": "Engine Surface Cleaner",
    "nombre": "Limpiador de Superficie del Motor Maximum Engine Surface Cleaner Expert – 311 GR",
    "descripcion": "",
    "image": "imgproductos/nuevos/taller_engine_surface_cleaner.png",
    "alt": "Limpiador de Superficie del Motor Maximum Engine Surface Cleaner Expert – 311 GR",
    "status": "valid",
    "slug": "engine-surface-cleaner-desengrasante-para-motor-395-ml",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 490,
    "pdf": null
  },
  {
    "id": 111,
    "numero": 111,
    "nombreOriginal": "Creativo Motor Cool 55%",
    "nombre": "Creativo Motor Cool 55% Aditivado para Todo Tipo de Vehículo",
    "descripcion": "",
    "image": "imgproductos/creativo_111.jpeg",
    "alt": "Creativo Motor Cool 55% Aditivado para Todo Tipo de Vehículo",
    "status": "hidden",
    "slug": "creativo-motor-cool-55-aditivado-para-todo-tipo-de-vehculo",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 112,
    "numero": 112,
    "nombreOriginal": "Agua Químicamente Pura 1 galón",
    "nombre": "Agua Químicamente Pura AQP 1 Galón",
    "descripcion": "",
    "image": "imgproductos/creativo_112.jpg",
    "alt": "Agua Químicamente Pura AQP 1 Galón",
    "status": "hidden",
    "slug": "agua-qumicamente-pura-aqp-1-galn",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 113,
    "numero": 113,
    "nombreOriginal": "Antiempañante",
    "nombre": "Tratamiento Antiempañante para Vidrios Maximum Antifog – 120 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/carcare_antiempanante.png",
    "alt": "Tratamiento Antiempañante para Vidrios Maximum Antifog – 120 ml",
    "status": "valid",
    "slug": "spray-antiempaante-para-vidrios-y-espejos",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 640,
    "pdf": null
  },
  {
    "id": 114,
    "numero": 114,
    "nombreOriginal": "Creativo DOT4",
    "nombre": "Creativo Líquido de Frenos DOT4 Ultra 230°C",
    "descripcion": "",
    "image": "imgproductos/creativo_114.jpeg",
    "alt": "Creativo Líquido de Frenos DOT4 Ultra 230°C",
    "status": "hidden",
    "slug": "creativo-lquido-de-frenos-dot4-ultra-230c",
    "category": "Frenos",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 115,
    "numero": 115,
    "nombreOriginal": "Agua para baterías y radiadores",
    "nombre": "Agua Desionizada y Desmineralizada para Baterías y Radiadores",
    "descripcion": "",
    "image": "imgproductos/creativo_115.jpg",
    "alt": "Agua Desionizada y Desmineralizada para Baterías y Radiadores",
    "status": "hidden",
    "slug": "agua-desionizada-y-desmineralizada-para-bateras-y-radiadores",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 116,
    "numero": 116,
    "nombreOriginal": "DOT3",
    "nombre": "Líquido de Frenos DOT3 Ultra 354 ml",
    "descripcion": "",
    "image": "imgproductos/creativo_116.png",
    "alt": "Líquido de Frenos DOT3 Ultra 354 ml",
    "status": "hidden",
    "slug": "lquido-de-frenos-dot3-ultra-354-ml",
    "category": "Frenos",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 117,
    "numero": 117,
    "nombreOriginal": "Brake Cleaner",
    "nombre": "Brake Cleaner Pro – Limpiador del Sistema de Frenos – 500 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/taller_brake_cleaner.png",
    "alt": "Brake Cleaner Pro – Limpiador del Sistema de Frenos – 500 ml",
    "status": "valid",
    "slug": "brake-cleaner-limpiador-profesional-para-sistema-de-frenos-500-ml",
    "category": "Frenos",
    "featured": false,
    "orderPriority": 520,
    "pdf": null
  },
  {
    "id": 118,
    "numero": 118,
    "nombreOriginal": "Creativo Ultra Black y Grey Force",
    "nombre": "Creativo Silicona para Empaquetadura Ultra Black y Grey Force 85 g",
    "descripcion": "",
    "image": "imgproductos/creativo_118.jpg",
    "alt": "Creativo Silicona para Empaquetadura Ultra Black y Grey Force 85 g",
    "status": "hidden",
    "slug": "creativo-silicona-para-empaquetadura-ultra-black-y-grey-force-85-g",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 2,
    "pdf": "FICHAS TECNICAS MAXIMUM/FICHA TECNICA SILICONA PARA EMPAQUETADURA, GREY FORCE - ULTRA BLACK. (6)"
  },
  {
    "id": 119,
    "numero": 119,
    "nombreOriginal": "Agua Químicamente Pura batería/radiador",
    "nombre": "Agua Químicamente Pura para Baterías, Radiadores y Uso Industrial",
    "descripcion": "",
    "image": "imgproductos/creativo_119.png",
    "alt": "Agua Químicamente Pura para Baterías, Radiadores y Uso Industrial",
    "status": "hidden",
    "slug": "agua-qumicamente-pura-para-bateras-radiadores-y-uso-industrial",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 2,
    "pdf": null
  },
  {
    "id": 120,
    "numero": 120,
    "nombreOriginal": "Siliconax Auto Brillo",
    "nombre": "SILICONAX Auto Brillo Silicon Restaurador y Protector 285 gr",
    "descripcion": "",
    "image": "imgproductos/nuevos/carcare_siliconax_pack.jpg",
    "alt": "SILICONAX Auto Brillo Silicon Restaurador y Protector 285 gr",
    "status": "hidden",
    "slug": "siliconax-auto-brillo-silicon-restaurador-285-gr",
    "category": "Carcare",
    "featured": true,
    "orderPriority": 330,
    "pdf": null
  },
  {
    "id": 121,
    "numero": 121,
    "nombreOriginal": "Bouquet ASH",
    "nombre": "Aromatizante Maximum Bouquet Ash 100% Orgánico",
    "descripcion": "",
    "image": "imgproductos/nuevos/carcare_bouquet_ash.png",
    "alt": "Aromatizante Maximum Bouquet Ash 100% Orgánico",
    "status": "valid",
    "slug": "bouquet-ash-ambientador-organico-46-gr",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 310,
    "pdf": null
  },
  {
    "id": 122,
    "numero": 122,
    "nombreOriginal": "Catalytic System Ultra-Clean S300",
    "nombre": "Catalytic System Ultra-Clean – Limpiador de Catalizador – 300 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/taller_catalytic_system.png",
    "alt": "Catalytic System Ultra-Clean – Limpiador de Catalizador – 300 ml",
    "status": "valid",
    "slug": "catalytic-system-ultra-clean-s300-300-ml",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 500,
    "pdf": null
  },
  {
    "id": 123,
    "numero": 123,
    "nombreOriginal": "Engine Flush Advanced F300",
    "nombre": "Engine Flush Advanced – Restaurador Interno del Motor – 300 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/taller_engine_flush.png",
    "alt": "Engine Flush Advanced – Restaurador Interno del Motor – 300 ml",
    "status": "valid",
    "slug": "engine-flush-advanced-f300-300-ml",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 480,
    "pdf": null
  },
  {
    "id": 124,
    "numero": 124,
    "nombreOriginal": "Extreme Under Coating GA500",
    "nombre": "Blindaje Automotriz Maximum Extreme Undercoating – 1 LITRO",
    "descripcion": "",
    "image": "imgproductos/nuevos/taller_under_coating.png",
    "alt": "Blindaje Automotriz Maximum Extreme Undercoating – 1 LITRO",
    "status": "valid",
    "slug": "extreme-under-coating-ga500-blindaje-automotriz",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 530,
    "pdf": null
  },
  {
    "id": 125,
    "numero": 125,
    "nombreOriginal": "Spray Zinc Oxid Free",
    "nombre": "Spray de Zinc OXID-FREE – Protección Galvanoplástica – 400 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/taller_spray_zinc.png",
    "alt": "Spray de Zinc OXID-FREE – Protección Galvanoplástica – 400 ml",
    "status": "valid",
    "slug": "spray-zinc-oxid-free-400-ml",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 510,
    "pdf": null
  },
  {
    "id": 126,
    "numero": 126,
    "nombreOriginal": "Siliconax Excelencia Premium",
    "nombre": "Siliconax Premium Maximum Brisa del Mar – 750 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/carcare_siliconax_excelencia.png",
    "alt": "Siliconax Premium Maximum Brisa del Mar – 750 ml",
    "status": "valid",
    "slug": "siliconax-excelencia-premium-350-ml",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 320,
    "pdf": null
  },
  {
    "id": 127,
    "numero": 127,
    "nombreOriginal": "Brake Fluid Liquid Tester HT662",
    "nombre": "Brake Fluid Liquid Tester HT662 Probador de Líquido de Frenos",
    "descripcion": "",
    "image": "imgproductos/nuevos/prod_127.png",
    "alt": "Brake Fluid Liquid Tester HT662 Probador de Líquido de Frenos",
    "status": "hidden",
    "slug": "brake-fluid-liquid-tester-ht662",
    "category": "Otros",
    "featured": false,
    "orderPriority": 280,
    "pdf": null
  },
  {
    "id": 128,
    "numero": 128,
    "nombreOriginal": "Brake Fluid Liquid Tester Digital",
    "nombre": "Detector Electrónico de Humedad para Líquido de Frenos DOT 3/4/5.1 Maximum",
    "descripcion": "",
    "image": "imgproductos/nuevos/detector-electronico-humedad-frenos-dot.png",
    "alt": "Detector Electrónico de Humedad para Líquido de Frenos DOT 3/4/5.1 Maximum",
    "status": "valid",
    "slug": "brake-fluid-liquid-tester-digital",
    "category": "Otros",
    "featured": false,
    "orderPriority": 290,
    "pdf": null
  },
  {
    "id": 129,
    "numero": 129,
    "nombreOriginal": "Kit Diagnóstico Sistema de Refrigeración",
    "nombre": "Kit Detector de Fugas para Radiador Maximum",
    "descripcion": "",
    "image": "imgproductos/nuevos/kit-detector-fugas-radiador.png",
    "alt": "Kit Detector de Fugas para Radiador Maximum",
    "status": "valid",
    "slug": "kit-profesional-diagnostico-sistema-refrigeracion",
    "category": "Otros",
    "featured": false,
    "orderPriority": 300,
    "pdf": null
  },
  {
    "id": 130,
    "numero": 130,
    "nombreOriginal": "Antifreeze & Coolant IBC 1000L",
    "nombre": "Bin de Plástico Industrial – 1000 Litros",
    "descripcion": "",
    "image": "imgproductos/nuevos/bin-plastico-industrial-1000l.png",
    "alt": "Bin de Plástico Industrial – 1000 Litros",
    "status": "valid",
    "slug": "refrigerante-antifreeze-coolant-50-ibc-1000-litros",
    "category": "Presentaciones",
    "featured": false,
    "orderPriority": 120,
    "pdf": null
  },
  {
    "id": 131,
    "numero": 131,
    "nombreOriginal": "Antifreeze & Coolant Balde 5 Galones Negro",
    "nombre": "Balde Heavy Duty – 5 Galones",
    "descripcion": "",
    "image": "imgproductos/nuevos/balde-heavy-duty-5gal.png",
    "alt": "Balde Heavy Duty – 5 Galones",
    "status": "valid",
    "slug": "refrigerante-antifreeze-coolant-50-balde-5-galones-negro",
    "category": "Presentaciones",
    "featured": false,
    "orderPriority": 120,
    "pdf": null
  },
  {
    "id": 132,
    "numero": 132,
    "nombreOriginal": "Siliconax Excelencia Premium Rojo Cereza",
    "nombre": "Siliconax Premium Maximum Cereza – 750 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/carcare_siliconax_rojo_cereza.png",
    "alt": "Siliconax Premium Maximum Cereza – 750 ml",
    "status": "valid",
    "slug": "siliconax-excelencia-premium-rojo-cereza-750-ml",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 320,
    "pdf": null
  },
  {
    "id": 133,
    "numero": 133,
    "nombreOriginal": "Siliconax Excelencia Premium Rosa",
    "nombre": "Siliconax Premium Maximum Chicle – 750 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/carcare_siliconax_rosa.png",
    "alt": "Siliconax Premium Maximum Chicle – 750 ml",
    "status": "valid",
    "slug": "siliconax-excelencia-premium-rosa-750-ml",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 320,
    "pdf": null
  },
  {
    "id": 134,
    "numero": 134,
    "nombreOriginal": "Siliconax Excelencia Premium Dorado Champagne",
    "nombre": "Siliconax Premium Maximum Vainilla – 750 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/carcare_siliconax_dorado_champagne.png",
    "alt": "Siliconax Premium Maximum Vainilla – 750 ml",
    "status": "valid",
    "slug": "siliconax-excelencia-premium-dorado-champagne-750-ml",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 320,
    "pdf": null
  },
  {
    "id": 135,
    "numero": 135,
    "nombreOriginal": "Siliconax Excelencia Premium Blanco",
    "nombre": "Siliconax Premium Maximum Jazmín – 750 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/carcare_siliconax_blanco.png",
    "alt": "Siliconax Premium Maximum Jazmín – 750 ml",
    "status": "valid",
    "slug": "siliconax-excelencia-premium-blanco-750-ml",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 320,
    "pdf": null
  },
  {
    "id": 136,
    "numero": 136,
    "nombreOriginal": "Siliconax Excelencia Premium Marrón",
    "nombre": "Siliconax Premium Maximum Sándalo – 750 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/carcare_siliconax_marron.png",
    "alt": "Siliconax Premium Maximum Sándalo – 750 ml",
    "status": "valid",
    "slug": "siliconax-excelencia-premium-marron-750-ml",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 320,
    "pdf": null
  },
  {
    "id": 137,
    "numero": 137,
    "nombreOriginal": "Siliconax Excelencia Premium Negro",
    "nombre": "Siliconax Premium Maximum Coche Nuevo – 750 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/carcare_siliconax_negro.png",
    "alt": "Siliconax Premium Maximum Coche Nuevo – 750 ml",
    "status": "valid",
    "slug": "siliconax-excelencia-premium-negro-750-ml",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 320,
    "pdf": null
  },
  {
    "id": 138,
    "numero": 138,
    "nombreOriginal": "Siliconax Excelencia Premium Amarillo",
    "nombre": "Siliconax Premium Maximum Limón – 750 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/carcare_siliconax_amarillo.png",
    "alt": "Siliconax Premium Maximum Limón – 750 ml",
    "status": "valid",
    "slug": "siliconax-excelencia-premium-amarillo-750-ml",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 320,
    "pdf": null
  },
  {
    "id": 139,
    "numero": 139,
    "nombreOriginal": "Siliconax Excelencia Premium Verde",
    "nombre": "Siliconax Premium Maximum Floral – 750 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/carcare_siliconax_verde.png",
    "alt": "Siliconax Premium Maximum Floral – 750 ml",
    "status": "valid",
    "slug": "siliconax-excelencia-premium-verde-750-ml",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 320,
    "pdf": null
  },
  {
    "id": 140,
    "numero": 140,
    "nombreOriginal": "Siliconax Excelencia Premium Azul Marino",
    "nombre": "Siliconax Premium Maximum Océano – 750 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/carcare_siliconax_azul_marino.png",
    "alt": "Siliconax Premium Maximum Océano – 750 ml",
    "status": "valid",
    "slug": "siliconax-excelencia-premium-azul-marino-750-ml",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 320,
    "pdf": null
  },
  {
    "id": 141,
    "numero": 141,
    "nombreOriginal": "Siliconax Excelencia Premium Rojo Brillante",
    "nombre": "Siliconax Premium Maximum Fresa – 750 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/carcare_siliconax_rojo_brillante.png",
    "alt": "Siliconax Premium Maximum Fresa – 750 ml",
    "status": "valid",
    "slug": "siliconax-excelencia-premium-rojo-brillante-750-ml",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 320,
    "pdf": null
  },
  {
    "id": 142,
    "numero": 142,
    "nombreOriginal": "Siliconax Excelencia Premium Verde Menta",
    "nombre": "Siliconax Premium Maximum Menta – 750 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/carcare_siliconax_verde_menta.png",
    "alt": "Siliconax Premium Maximum Menta – 750 ml",
    "status": "valid",
    "slug": "siliconax-excelencia-premium-verde-menta-750-ml",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 320,
    "pdf": null
  },
  {
    "id": 143,
    "numero": 143,
    "nombreOriginal": "Siliconax Excelencia Premium Bronce",
    "nombre": "Siliconax Premium Maximum Gardenia – 750 ml",
    "descripcion": "",
    "image": "imgproductos/nuevos/carcare_siliconax_bronce.png",
    "alt": "Siliconax Premium Maximum Gardenia – 750 ml",
    "status": "valid",
    "slug": "siliconax-excelencia-premium-bronce-750-ml",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 320,
    "pdf": null
  },
  {
    "id": 147,
    "nombre": "Refrigerante Maximum Antifreeze & Coolant OAT 17% Verde Reflex – 1 Litro",
    "descripcion": "Refrigerante y anticongelante OAT. Listo para usar, no agregar agua. Verde Reflex fluorescente. 1 Qt.",
    "image": "imgproductos/nuevos/antifreeze-17-verde-reflex-1qt.png",
    "alt": "Refrigerante Maximum Antifreeze & Coolant OAT 17% Verde Reflex – 1 Litro",
    "status": "valid",
    "slug": "antifreeze-coolant-17-verde-reflex-1qt",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 112,
    "pdf": null
  },
  {
    "id": 148,
    "nombre": "Refrigerante Maximum Antifreeze & Coolant OAT 33% Verde Reflex – 1 Litro",
    "descripcion": "Refrigerante y anticongelante OAT. Listo para usar, no agregar agua. Verde Reflex fluorescente. 1 Qt.",
    "image": "imgproductos/nuevos/antifreeze-33-verde-reflex-1qt.png",
    "alt": "Refrigerante Maximum Antifreeze & Coolant OAT 33% Verde Reflex – 1 Litro",
    "status": "valid",
    "slug": "antifreeze-coolant-33-verde-reflex-1qt",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 114,
    "pdf": null
  },
  {
    "id": 149,
    "nombre": "Refrigerante Maximum Antifreeze & Coolant OAT 33% Rojo Reflex – 1 Litro",
    "descripcion": "Refrigerante y anticongelante OAT. Listo para usar, no agregar agua. Rojo Reflex fluorescente. 1 Qt.",
    "image": "imgproductos/nuevos/antifreeze-33-rojo-reflex-1qt.png",
    "alt": "Refrigerante Maximum Antifreeze & Coolant OAT 33% Rojo Reflex – 1 Litro",
    "status": "valid",
    "slug": "antifreeze-coolant-33-rojo-reflex-1qt",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 116,
    "pdf": null
  },
  {
    "id": 150,
    "nombre": "Refrigerante Maximum Antifreeze & Coolant OAT 50% Verde Reflex – 1 Litro",
    "descripcion": "Refrigerante y anticongelante OAT. Listo para usar, no agregar agua. Verde Reflex fluorescente. 1 Qt.",
    "image": "imgproductos/nuevos/antifreeze-50-verde-reflex-1qt.png",
    "alt": "Refrigerante Maximum Antifreeze & Coolant OAT 50% Verde Reflex – 1 Litro",
    "status": "valid",
    "slug": "antifreeze-coolant-50-verde-reflex-1qt",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 118,
    "pdf": null
  },
  {
    "id": 151,
    "nombre": "Refrigerante Maximum Antifreeze & Coolant OAT 50% Rojo Reflex – 1 Litro",
    "descripcion": "Refrigerante y anticongelante OAT. Listo para usar, no agregar agua. Rojo Reflex fluorescente. 1 Qt.",
    "image": "imgproductos/nuevos/antifreeze-50-rojo-reflex-1qt.png",
    "alt": "Refrigerante Maximum Antifreeze & Coolant OAT 50% Rojo Reflex – 1 Litro",
    "status": "valid",
    "slug": "antifreeze-coolant-50-rojo-reflex-1qt",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 119,
    "pdf": null
  },
  {
    "id": 144,
    "nombre": "Silicona Líquida Multisuperficies Maximum Siliconax Limón – 285 GR",
    "descripcion": "Silicon restaurador y protector multi superficies. Tecnología Surface Guard. 285 g.",
    "image": "imgproductos/nuevos/siliconax-autobrillo-limon-285g.jpg",
    "alt": "Silicona Líquida Multisuperficies Maximum Siliconax Limón – 285 GR",
    "status": "valid",
    "slug": "siliconax-autobrillo-limon-285g",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 311,
    "pdf": null
  },
  {
    "id": 145,
    "nombre": "Silicona Líquida Multisuperficies Maximum Siliconax Frutal – 285 GR",
    "descripcion": "Silicon restaurador y protector multi superficies. Tecnología Surface Guard. 285 g.",
    "image": "imgproductos/nuevos/siliconax-autobrillo-frutal-285g.jpg",
    "alt": "Silicona Líquida Multisuperficies Maximum Siliconax Frutal – 285 GR",
    "status": "valid",
    "slug": "siliconax-autobrillo-frutal-285g",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 312,
    "pdf": null
  },
  {
    "id": 146,
    "nombre": "Silicona Líquida Multisuperficies Maximum Siliconax Océano – 285 GR",
    "descripcion": "Silicon restaurador y protector multi superficies. Tecnología Surface Guard. 285 g.",
    "image": "imgproductos/nuevos/siliconax-autobrillo-oceano-285g.jpg",
    "alt": "Silicona Líquida Multisuperficies Maximum Siliconax Océano – 285 GR",
    "status": "valid",
    "slug": "siliconax-autobrillo-oceano-285g",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 313,
    "pdf": null
  }
,
  {
    "id": 152,
    "nombre": "Refrigerante Maximum Antifreeze & Coolant OAT 17% Verde Reflex – 5 Galones",
    "descripcion": "Refrigerante y anticongelante OAT. Verde Reflex fluorescente. 5 Galones.",
    "image": "imgproductos/nuevos/antifreeze-17-verde-reflex-5gal.png",
    "alt": "Refrigerante Maximum Antifreeze & Coolant OAT 17% Verde Reflex – 5 Galones",
    "status": "valid",
    "slug": "antifreeze-coolant-oat-17-verde-reflex-5gal",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 113,
    "pdf": null
  },
  {
    "id": 153,
    "nombre": "Refrigerante Maximum Antifreeze & Coolant OAT 33% Rojo Reflex – 5 Galones",
    "descripcion": "Refrigerante y anticongelante OAT. Rojo Reflex fluorescente. 5 Galones.",
    "image": "imgproductos/nuevos/antifreeze-33-rojo-reflex-5gal.png",
    "alt": "Refrigerante Maximum Antifreeze & Coolant OAT 33% Rojo Reflex – 5 Galones",
    "status": "valid",
    "slug": "antifreeze-coolant-oat-33-rojo-reflex-5gal",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 117,
    "pdf": null
  },
  {
    "id": 154,
    "nombre": "Refrigerante Maximum Antifreeze & Coolant OAT 33% Verde Reflex – 5 Galones",
    "descripcion": "Refrigerante y anticongelante OAT. Verde Reflex fluorescente. 5 Galones.",
    "image": "imgproductos/nuevos/antifreeze-33-verde-reflex-5gal.png",
    "alt": "Refrigerante Maximum Antifreeze & Coolant OAT 33% Verde Reflex – 5 Galones",
    "status": "valid",
    "slug": "antifreeze-coolant-oat-33-verde-reflex-5gal",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 115,
    "pdf": null
  },
  {
    "id": 155,
    "nombre": "Refrigerante Maximum Antifreeze & Coolant OAT 50% Rojo Reflex – 5 Galones",
    "descripcion": "Refrigerante y anticongelante OAT. Rojo Reflex fluorescente. 5 Galones.",
    "image": "imgproductos/nuevos/antifreeze-50-rojo-reflex-5gal.png",
    "alt": "Refrigerante Maximum Antifreeze & Coolant OAT 50% Rojo Reflex – 5 Galones",
    "status": "valid",
    "slug": "antifreeze-coolant-oat-50-rojo-reflex-5gal",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 121,
    "pdf": null
  },
  {
    "id": 156,
    "nombre": "Refrigerante Maximum Motor Cool HD OAT 55/45 Rojo – 5 Galones",
    "descripcion": "Refrigerante Motor Cool HD Heavy Duty en presentación 5 Galones.",
    "image": "imgproductos/nuevos/motorcoolhd-rojo-5gal.png",
    "alt": "Refrigerante Maximum Motor Cool HD OAT 55/45 Rojo – 5 Galones",
    "status": "valid",
    "slug": "motorcoolhd-oat-55-45-rojo-5gal",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 85,
    "pdf": null
  },
  {
    "id": 157,
    "nombre": "Refrigerante Maximum Motor Cool 60/40 Rojo Reflex para Vehículos GLP/GNV – 1 Litro",
    "descripcion": "Refrigerante Motor Cool GLP/GNV en presentación 1 Litro. Rojo Reflex fluorescente.",
    "image": "imgproductos/nuevos/motorcool-glpgnv-rojo-1litro.png",
    "alt": "Refrigerante Maximum Motor Cool 60/40 Rojo Reflex para Vehículos GLP/GNV – 1 Litro",
    "status": "valid",
    "slug": "motorcool-60-40-rojo-reflex-glpgnv-1litro",
    "category": "Refrigerantes",
    "featured": false,
    "orderPriority": 101,
    "pdf": null
  }
,
  {
    "id": 158,
    "nombre": "Agua Químicamente Pura Maximum Desionizada y Desmineralizada – 1 Litro",
    "descripcion": "Agua pura desionizada y desmineralizada. Presentación 1 Litro.",
    "image": "imgproductos/nuevos/agua-pura-1litro-carcare.jpg",
    "alt": "Agua Químicamente Pura Maximum Desionizada y Desmineralizada – 1 Litro",
    "status": "valid",
    "slug": "agua-pura-desionizada-1litro",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 660,
    "pdf": null
  },
  {
    "id": 159,
    "nombre": "Agua Químicamente Pura Maximum Desionizada y Desmineralizada – 5 Litros",
    "descripcion": "Agua pura desionizada y desmineralizada. Presentación 5 Litros.",
    "image": "imgproductos/nuevos/agua-pura-5litros-carcare.jpg",
    "alt": "Agua Químicamente Pura Maximum Desionizada y Desmineralizada – 5 Litros",
    "status": "valid",
    "slug": "agua-pura-desionizada-5litros",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 662,
    "pdf": null
  },
  {
    "id": 160,
    "nombre": "Shampoo con Cera Maximum High Efficiency – 5 Litros",
    "descripcion": "Shampoo con cera de alta eficiencia para lavado profesional. 5 Litros.",
    "image": "imgproductos/nuevos/shampoo-high-efficiency-5litros.png",
    "alt": "Shampoo con Cera Maximum High Efficiency – 5 Litros",
    "status": "valid",
    "slug": "shampoo-high-efficiency-5litros",
    "category": "Carcare",
    "featured": false,
    "orderPriority": 613,
    "pdf": null
  }
,
  {
    "id": 161,
    "nombre": "Grasa de Cadena en Spray Antióxido – 450 g",
    "image": "imgproductos/nuevos/grasa-cadena-spray-antioxido-450g.png",
    "status": "valid",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 540,
    "alt": "Grasa de Cadena en Spray Antióxido 450g Maximum",
    "slug": "grasa-cadena-spray-antioxido-450g",
    "descripcion": "",
    "pdf": ""
  },
  {
    "id": 162,
    "nombre": "Grasa de Cadena en Spray Maximum Alta Temperatura – 450 g",
    "image": "imgproductos/nuevos/grasa-cadena-spray-alta-temperatura-450g.png",
    "status": "valid",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 550,
    "alt": "Grasa de Cadena en Spray Alta Temperatura 450g Maximum",
    "slug": "grasa-cadena-spray-alta-temperatura-450g",
    "descripcion": "",
    "pdf": ""
  },
  {
    "id": 163,
    "nombre": "Grasa de Cadena en Spray Multipropósito – 450 g",
    "image": "imgproductos/nuevos/grasa-cadena-spray-multiproposito-450g.png",
    "status": "valid",
    "category": "Químicos de Taller",
    "featured": false,
    "orderPriority": 560,
    "alt": "Grasa de Cadena en Spray Multipropósito 450g Maximum",
    "slug": "grasa-cadena-spray-multiproposito-450g",
    "descripcion": "",
    "pdf": ""
  }
,
  {
    "id": 164,
    "nombre": "Envase Compacto – 1/4 Galón",
    "image": "imgproductos/nuevos/envase-compacto-cuarto-galon.png",
    "status": "valid",
    "category": "Presentaciones",
    "featured": false,
    "orderPriority": 285,
    "alt": "Envase Compacto 1/4 Galón Maximum",
    "slug": "envase-compacto-cuarto-galon",
    "descripcion": "",
    "pdf": ""
  },
  {
    "id": 165,
    "nombre": "Envase Performance – 1 Galón",
    "image": "imgproductos/nuevos/envase-performance-1galon.jpg",
    "status": "valid",
    "category": "Presentaciones",
    "featured": false,
    "orderPriority": 290,
    "alt": "Envase Performance 1 Galón Maximum",
    "slug": "envase-performance-1galon",
    "descripcion": "",
    "pdf": ""
  }
,
  {
    "id": 166,
    "nombre": "Grasa de Complejo de Litio Multipropósito Maximum Gralimax EP3",
    "image": "imgproductos/nuevos/grasa-gralimax-ep3.png",
    "status": "valid",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 365,
    "alt": "Grasa de Complejo de Litio Multipropósito Maximum Gralimax EP3",
    "slug": "grasa-gralimax-ep3",
    "descripcion": "",
    "pdf": ""
  },
  {
    "id": 167,
    "nombre": "Grasa de Complejo de Litio Multipropósito Maximum Gralimax EP3 – Balde 5 kg",
    "image": "imgproductos/nuevos/grasa-gralimax-ep3-balde-5kg.png",
    "status": "valid",
    "category": "Grasas",
    "featured": false,
    "orderPriority": 368,
    "alt": "Grasa de Complejo de Litio Multipropósito Maximum Gralimax EP3 Balde 5 kg",
    "slug": "grasa-gralimax-ep3-balde-5kg",
    "descripcion": "",
    "pdf": ""
  }
,
  {
    "id": 168,
    "nombre": "Detector de Humedad para Líquido de Frenos Maximum",
    "image": "imgproductos/nuevos/detector-humedad-liquido-frenos.png",
    "status": "valid",
    "category": "Otros",
    "featured": false,
    "orderPriority": 295,
    "alt": "Detector de Humedad para Líquido de Frenos Maximum",
    "slug": "detector-humedad-liquido-frenos",
    "descripcion": "",
    "pdf": ""
  },
  {
    "id": 169,
    "nombre": "Refractómetro Digital Maximum para Medir Etilenglicol",
    "image": "imgproductos/nuevos/refractometro-digital-etilenglicol.png",
    "status": "valid",
    "category": "Otros",
    "featured": false,
    "orderPriority": 310,
    "alt": "Refractómetro Digital Maximum para Medir Etilenglicol",
    "slug": "refractometro-digital-etilenglicol",
    "descripcion": "",
    "pdf": ""
  }
,
  {
    "id": 170,
    "nombre": "Envase Compacto – 1/4 Galón",
    "image": "imgproductos/nuevos/envase-compacto-cuarto-galon-2.png",
    "status": "valid",
    "category": "Presentaciones",
    "featured": false,
    "orderPriority": 286,
    "alt": "Envase Compacto 1/4 Galón Maximum variante",
    "slug": "envase-compacto-cuarto-galon-2",
    "descripcion": "",
    "pdf": ""
  },
  {
    "id": 171,
    "nombre": "Envase Performance – 1 Galón",
    "image": "imgproductos/nuevos/envase-performance-1galon-2.jpg",
    "status": "valid",
    "category": "Presentaciones",
    "featured": false,
    "orderPriority": 291,
    "alt": "Envase Performance 1 Galón Maximum variante",
    "slug": "envase-performance-1galon-2",
    "descripcion": "",
    "pdf": ""
  },
  {
    "id": 172,
    "nombre": "Refrigerante Maximum Motor Cool HD OAT 55/45 Rojo – 5 Galones",
    "image": "imgproductos/nuevos/motorcoolhd-rojo-5gal-presentacion.jpg",
    "status": "valid",
    "category": "Presentaciones",
    "featured": false,
    "orderPriority": 295,
    "alt": "Refrigerante Maximum Motor Cool HD Rojo 5 Galones",
    "slug": "motorcoolhd-rojo-5gal-presentacion",
    "descripcion": "",
    "pdf": ""
  }
];